#!/bin/bash

set_listen_addresses() {
	sedEscapedValue="$(echo "$1" | sed 's/[\/&]/\\&/g')"
	sed -ri "s/^#?(listen_addresses\s*=\s*)\S+/\1'$sedEscapedValue'/" "$POSTGRESQL_CONF"
}


function check_postgres_environment {
    if [ ! -v DATA_PATH ]; then
        DATA_PATH="/data"
        export DATA_PATH
    fi
    if [ ! -v LOG_PATH ]; then
        LOG_PATH="/logs"
        export LOG_PATH
    fi
}

function postgresInformation {
    displayInformation $1
    echo $1 "version   : $SX_VERSION"
    echo $1 "engine    : $(postgres -V | head -1)"
    echo $1 "sql path  : $LOADSQL_PATH"
    echo $1 "log path  : $LOG_PATH"
    echo $1 "data path : $DATA_PATH"
}

function displayPostgresRunInformation {
    postgresInformation $1
    echo $1 "admin     : root:$PGSQL_ROOT_PASSWORD"
    echo $1 "user      : $PGSQL_USER:$PGSQL_PASSWORD"
    echo $1 "database  : $PGSQL_DATABASE"
}

function postgresPreDeploy {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running PRE-DEPLOY HOOK"
    echoVerbose "| "
    echoVerbose `postgresInformation "| "`
    echo "+====================================================="
}

function postgresPostDeploy {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running POST-DEPLOY HOOK"
    echoVerbose "| "
    echoVerbose `postgresInformation "| "`
    echo "+====================================================="
}

function postgresPostBuild {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running POST-BUILD HOOK"
    echoVerbose "| "
    echoVerbose `postgresInformation "| "`
    echo "+====================================================="
}

function postgresAssemble {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running ASSEMBLE"
    echoVerbose "| "
    echoVerbose `postgresInformation "| "`
    echo "+====================================================="
    echo "Remove unused /tmp/src"
    rm -rf /tmp/src/.git
    echo "Fixing perm on /tmp/src"
    chown 1001:0 -R /tmp/src
    chmod g=u -R /tmp/src
}

function postgresRun {
    echo "+====================================================="
    echo "| Container $HOSTNAME is RUNNING"
    echoVerbose "| "
    echoVerbose `postgresInformation "| "`
    echo "+====================================================="
    startPostgresService
}

function stop_postgres_handler {
    postgres -c "pg_ctl stop -D $DATA_PATH -w"
    echo "+====================================================="
    echo "| Container $HOSTNAME is now STOPPED"
    echoVerbose "| "
    echoVerbose `postgresInformation "| "`
    echo "+====================================================="
    exit 143; # 128 + 15 -- SIGTERM
}

# Start the postgres server as a deamon and execute it inside 
# the running shell
function startPostgresService {
    trap 'kill ${!}; stop_postgres_handler' SIGHUP SIGINT SIGQUIT SIGTERM SIGKILL SIGSTOP SIGCONT
    exec postgres -c "pg_ctl start -D $DATA_PATH -w "
}