#!/bin/bash

# This is the GitLab CI/CD configuration file for sxcm kubernetes cluster manager.
#
# For more information, see: https://sxcm.readthedocs.io

# Global environment variables
variables:
  SXDI_GIT_DOMAIN: gitlab.com
  SXDI_GIT_SSH_USER: git@gitlab.com
  SX_VERBOSE: "true"
  SX_DEBUG: "true"

# Default container image
image: "quay.io/startx/runner-bash:alpine3"

# # Include library
# include:
#   - template: Security/SAST.gitlab-ci.yml

# Stagging for this pipeline
stages:
  - "check"
  - "test"
  - "build OS"
  - "build basic"
  - "build Services"
  - "build Runners"
  - "build VDI"
  - "build Application"

##
## LIBRARY
##

# Library used to merge branch in a local repo
.build-image:
  variables:
    SXDI_PATH: 'OS' # default to OS image
    SXDI_DOCKERNAME: 'fedora' # image name in docker.io registry
    SXDI_QUAYNAME: 'fedora' # image name in quay.io registry
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script: 
    - "source .gitlab-ci.sh && DoImageBuildPrepare"
  script:
    - DoImageBuildExecute $SXDI_PATH $SXDI_DOCKERNAME $SXDI_QUAYNAME startx
    - DoImageBuildTest $SXDI_PATH $SXDI_DOCKERNAME $SXDI_QUAYNAME startx
    - DoImageBuildPublish $SXDI_PATH $SXDI_DOCKERNAME $SXDI_QUAYNAME startx

##
## STAGES
##

# Return debug informations on master branch
debug:
  stage: "check"
  script: "source .gitlab-ci.sh && DisplayCheckDebug"
  only:
    - master

# Return informations details on master branch
info:
  stage: "check"
  script: "source .gitlab-ci.sh && DisplayCheckInfo"
  only:
    - master

# Requirements check on master branch
requirements:
  stage: "check"
  script: "source .gitlab-ci.sh && DisplayCheckRequirements"
  only:
    - master

# Markdown check on master branch
markdown:
  stage: "check"
  script: "source .gitlab-ci.sh && DisplayCheckMarkdown"
  only:
    - master

# Readthedocs check on master branch
readthedocs:
  stage: "check"
  script: "source .gitlab-ci.sh && DisplayCheckReadthedocs"
  only:
    - master

# Shell check on master branch
shell:
  stage: "check"
  script: "source .gitlab-ci.sh && DisplayCheckShellcheck"
  only:
    - master

# #Second stage; only dev branch
# bats:
#   stage: "test"
#   script: "cd tests && ./start.sh"
#   only:
#     - master

## Build image

# Build the fedora image
build-os:
  stage: "build OS"
  extends: .build-image
  variables:
    SXDI_PATH: 'OS'
    SXDI_DOCKERNAME: 'fedora'
    SXDI_QUAYNAME: 'fedora'
  only:
    - master

# Build the apache image 
build-apache:
  stage: "build basic"
  extends: .build-image
  variables:
    SXDI_PATH: 'Services/apache'
    SXDI_DOCKERNAME: 'sv-apache'
    SXDI_QUAYNAME: 'apache'
  only:
    - master

# Build the couchbase image 
build-couchbase:
  stage: "build Services"
  extends: .build-image
  variables:
    SXDI_PATH: 'Services/couchbase'
    SXDI_DOCKERNAME: 'sv-couchbase'
    SXDI_QUAYNAME: 'couchbase'
  only:
    - master

# Build the mariadb image 
build-mariadb:
  stage: "build Services"
  extends: .build-image
  variables:
    SXDI_PATH: 'Services/mariadb'
    SXDI_DOCKERNAME: 'sv-mariadb'
    SXDI_QUAYNAME: 'mariadb'
  only:
    - master

# Build the memcache image 
build-memcache:
  stage: "build Services"
  extends: .build-image
  variables:
    SXDI_PATH: 'Services/memcache'
    SXDI_DOCKERNAME: 'sv-memcache'
    SXDI_QUAYNAME: 'memcache'
  only:
    - master

# Build the mongo image 
build-mongo:
  stage: "build Services"
  extends: .build-image
  variables:
    SXDI_PATH: 'Services/mongo'
    SXDI_DOCKERNAME: 'sv-mongo'
    SXDI_QUAYNAME: 'mongo'
  only:
    - master

# Build the nodejs image 
build-nodejs:
  stage: "build basic"
  extends: .build-image
  variables:
    SXDI_PATH: 'Services/nodejs'
    SXDI_DOCKERNAME: 'sv-nodejs'
    SXDI_QUAYNAME: 'nodejs'
  only:
    - master

# Build the ooconv image 
build-ooconv:
  stage: "build Services"
  extends: .build-image
  variables:
    SXDI_PATH: 'Services/ooconv'
    SXDI_DOCKERNAME: 'sv-ooconv'
    SXDI_QUAYNAME: 'ooconv'
  only:
    - master

# Build the php image 
build-php:
  stage: "build Services"
  extends: .build-image
  variables:
    SXDI_PATH: 'Services/php'
    SXDI_DOCKERNAME: 'sv-php'
    SXDI_QUAYNAME: 'php'
  only:
    - master

# Build the postgres image 
build-postgres:
  stage: "build Services"
  extends: .build-image
  variables:
    SXDI_PATH: 'Services/postgres'
    SXDI_DOCKERNAME: 'sv-postgres'
    SXDI_QUAYNAME: 'postgres'
  only:
    - master

# Build the ansible gitlab-runner image 
build-runner-ansible:
  stage: "build Runners"
  extends: .build-image
  variables:
    SXDI_PATH: 'GitlabRunner/ansible'
    SXDI_DOCKERNAME: 'runner-ansible'
    SXDI_QUAYNAME: 'runner-ansible'
  only:
    - master

# Build the apache gitlab-runner image 
build-runner-apache:
  stage: "build Runners"
  extends: .build-image
  variables:
    SXDI_PATH: 'GitlabRunner/apache'
    SXDI_DOCKERNAME: 'runner-apache'
    SXDI_QUAYNAME: 'runner-apache'
  only:
    - master

# Build the bash gitlab-runner image 
build-runner-bash:
  stage: "build basic"
  extends: .build-image
  variables:
    SXDI_PATH: 'GitlabRunner/bash'
    SXDI_DOCKERNAME: 'runner-bash'
    SXDI_QUAYNAME: 'runner-bash'
  only:
    - master

# Build the nodejs gitlab-runner image 
build-runner-nodejs:
  stage: "build Runners"
  extends: .build-image
  variables:
    SXDI_PATH: 'GitlabRunner/nodejs'
    SXDI_DOCKERNAME: 'runner-nodejs'
    SXDI_QUAYNAME: 'runner-nodejs'
  only:
    - master

# Build the oc gitlab-runner image 
build-runner-oc:
  stage: "build Runners"
  extends: .build-image
  variables:
    SXDI_PATH: 'GitlabRunner/oc'
    SXDI_DOCKERNAME: 'runner-oc'
    SXDI_QUAYNAME: 'runner-oc'
  only:
    - master

# Build the php gitlab-runner image 
build-runner-php:
  stage: "build Runners"
  extends: .build-image
  variables:
    SXDI_PATH: 'GitlabRunner/php'
    SXDI_DOCKERNAME: 'runner-php'
    SXDI_QUAYNAME: 'runner-php'
  only:
    - master

# Build the chrome VDI image 
build-vdi-chrome:
  stage: "build VDI"
  extends: .build-image
  variables:
    SXDI_PATH: 'VDI/chrome'
    SXDI_DOCKERNAME: 'vdi-chrome'
    SXDI_QUAYNAME: 'chrome'
  only:
    - master

# Build the firefox VDI image 
build-vdi-firefox:
  stage: "build VDI"
  extends: .build-image
  variables:
    SXDI_PATH: 'VDI/firefox'
    SXDI_DOCKERNAME: 'vdi-firefox'
    SXDI_QUAYNAME: 'firefox'
  only:
    - master

# Build the AWX application image 
build-application-awx:
  stage: "build Application"
  extends: .build-image
  variables:
    SXDI_PATH: 'Applications/awx'
    SXDI_DOCKERNAME: 'app-awx'
    SXDI_QUAYNAME: 'awx'
  only:
    - master

# Build the phpmyadmin application image 
build-application-phpmyadmin:
  stage: "build Application"
  extends: .build-image
  variables:
    SXDI_PATH: 'Applications/phpmyadmin'
    SXDI_DOCKERNAME: 'app-phpmyadmin'
    SXDI_QUAYNAME: 'phpmyadmin'
  only:
    - master

# Build the rockmongo application image 
build-application-rockmongo:
  stage: "build Application"
  extends: .build-image
  variables:
    SXDI_PATH: 'Applications/rockmongo'
    SXDI_DOCKERNAME: 'app-rockmongo'
    SXDI_QUAYNAME: 'rockmongo'
  only:
    - master