version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.7"
  jobs:
    pre_install:
      - pip install mkdocs-material
mkdocs:
  configuration: mkdocs.yml
# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: .gitlab/ci/rtd-requirements.txt
formats:
  - epub
  - pdf
search:
  ranking:
    index.md: 10
    development.md: -4
    OS/*: 8
    Services/*: 7
    VDI/*: 3
    GitlabRunner/*: 5
  ignore:
    - 404.html
