app-pma:
  extends:
    file: Applications/phpmyadmin/docker-compose.yml
    service: phpmyadmin

#app-rockmongo:
#  extends:
#    file: Applications/rockmongo/docker-compose.yml
#    service: rockmongo
