#!/bin/bash
source $SX_LIBDIR/sx

# Display oc information
function runnerOcInformation {
    genericAllInformation $1 
    echoVerbose $1 "runner oc  : " `oc --version`
    echoVerbose $1 "runner make : " `make --version | head -n 1`
}
