#!/bin/bash
source /var/lib/sx/sx
source /var/lib/sx/sx-apache

# Display php information
function phpInformation {
    apacheInformation $1 
    echoVerbose $1 "php       : $(php --version | head -1)" 
}

# function executed when pre-deploy hook is called
function phpPreDeploy {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running PRE-DEPLOY HOOK"
    echoVerbose "| "
    phpInformation "| "
    echo "+====================================================="
    echo "Create log directory $LOG_PATH"
    touch $LOG_PATH/access.log
    testAndRunSourceCodeScript "pre-deploy" 
}

# function executed when post-deploy hook is called
function phpPostDeploy {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running POST-DEPLOY HOOK"
    echoVerbose "| "
    phpInformation "| "
    echo "+====================================================="
    testAndRunSourceCodeScript "post-deploy" 
}

# function executed when pre-build hook is called
function phpPostBuild {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running POST-BUILD HOOK"
    echoVerbose "| "
    phpInformation "| "
    echo "+====================================================="
    testAndRunSourceCodeScript "post-build" 
}

# function executed when assemble hook is called
function phpAssemble {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running ASSEMBLE"
    echoVerbose "| "
    phpInformation "| "
    echo "+====================================================="
    if [[ -d $S2I_DEST ]]; then
        echo "Fixing perm on $S2I_DEST"
        chmod g=u -R $S2I_DEST
        cp -R $S2I_DEST/* $APP_PATH/
        moveSourceCode $S2I_DEST $APP_PATH
    fi
    testAndRunSourceCodeScript "assemble" 
}

# function executed on container startup
function phpRun {
    echo "+====================================================="
    echo "| Container $HOSTNAME is RUNNING"
    echoVerbose "| "
    phpInformation "| "
    echo "+====================================================="
    startApacheService
}

# Display liveness status
function phpIsLive {
    genericIsLive
}

# Display readyness status
function phpIsReady {
    apacheIsReady
}
