#!/bin/bash
source $SX_LIBDIR/sx
source $SX_LIBDIR/sx-apache

# Display php information
function phpInformation {
    apacheInformation $1 
    echoVerbose $1 "php       : $(php --version | head -1)" 
}

# function executed when build hook is called
function phpBuild {
    genericHeader
    echoNotVerbose "container $HOSTNAME executing Php BUILD"
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME executing Php BUILD"
    echoVerbose "| "
    phpInformation "| "
    echoDebug `env`
    echoVerbose "+====================================================="
    doPhpBuild
    if [[ -x $MYS2I_DEST/assemble ]]; then
        echoVerbose "Build source code found at $MYS2I_DEST/assemble"
        testAndRunSourceCodeScript "assemble" 
    else
        echoVerbose "No Build source code found at $MYS2I_DEST/assemble"
    fi
    exit 0;
}

# function performing Php build actions
function doPhpBuild {
    doApacheBuild
    echoNotVerbose "Build Php"
    echoVerbose ""
    echoVerbose "+====================================================="
    echoVerbose "| Build Php"
    echoVerbose "+====================================================="
}

# function executed when post-build hook is called
function phpPostBuild {
    genericHeader
    echoNotVerbose "container $HOSTNAME executing Php POST-BUILD"
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME executing Php POST-BUILD"
    echoVerbose "| "
    phpInformation "| "
    echoDebug `env`
    echoVerbose "+====================================================="
    doPhpPostBuild
    if [[ -x $MYS2I_DEST/assemble ]]; then
        echoVerbose "PostBuild source code found at $MYS2I_DEST/post-build"
        testAndRunSourceCodeScript "post-build" 
    else
        echoVerbose "No PostBuild source code found at $MYS2I_DEST/post-build"
    fi
    exit 0;
}

# function performing Php post-build actions
function doPhpPostBuild {
    doApachePostBuild
    echoNotVerbose "PostBuild Php"
    echoVerbose ""
    echoVerbose "+====================================================="
    echoVerbose "| PostBuild Php"
    echoVerbose "+====================================================="
}

# function executed when pre-deploy hook is called
function phpPreDeploy {
    genericHeader
    echoNotVerbose "container $HOSTNAME executing Php PRE-DEPLOY"
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME executing Php PRE-DEPLOY"
    echoVerbose "| "
    phpInformation "| "
    echoDebug `env`
    echoVerbose "+====================================================="
    doPhpPreDeploy
    if [[ -x $MYS2I_DEST/pre-deploy ]]; then
        echoVerbose "PreDeploy source code found at $MYS2I_DEST/pre-deploy"
        testAndRunSourceCodeScript "pre-deploy" 
    else
        echoVerbose "No PreDeploy source code found at $MYS2I_DEST/pre-deploy"
    fi
    exit 0;
}

# function performing Php pre-deploy actions
function doPhpPreDeploy {
    doApachePreDeploy
    echoNotVerbose "PreDeploy Php"
    echoVerbose ""
    echoVerbose "+====================================================="
    echoVerbose "| PreDeploy Php"
    echoVerbose "+====================================================="
}

# function executed when post-deploy hook is called
function phpPostDeploy {
    genericHeader
    echoNotVerbose "container $HOSTNAME executing Php POST-DEPLOY"
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME executing Php POST-DEPLOY"
    echoVerbose "| "
    phpInformation "| "
    echoDebug `env`
    echoVerbose "+====================================================="
    doPhpPostDeploy
    if [[ -x $MYS2I_DEST/post-deploy ]]; then
        echoVerbose "PostDeploy source code found at $MYS2I_DEST/post-deploy"
        testAndRunSourceCodeScript "post-deploy" 
    else
        echoVerbose "No PostDeploy source code found at $MYS2I_DEST/post-deploy"
    fi
    exit 0;
}

# function performing Php post-deploy actions
function doPhpPostDeploy {
    doApachePostDeploy
    echoNotVerbose "PostDeploy Php"
    echoVerbose ""
    echoVerbose "+====================================================="
    echoVerbose "| PostDeploy Php"
    echoVerbose "+====================================================="
}

# function executed on container startup
function phpRun {
    genericHeader
    echoNotVerbose "container $HOSTNAME executing Php RUN"
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME executing Php RUN"
    echoVerbose "| "
    phpInformation "| "
    echoDebug `env`
    echoVerbose "+====================================================="
    if [[ -x $MYS2I_DEST/run ]]; then
        echoVerbose "Run source code found at $MYS2I_DEST/run"
        testAndRunSourceCodeScript "run" 
    else
        echoVerbose "No Run source code found at $MYS2I_DEST/run"
        echoVerbose "Executing default Php run action"
        doPhpRun
    fi
}

# function performing Php run actions
function doPhpRun {
    echoNotVerbose "Run Php"
    echoVerbose ""
    echoVerbose "+====================================================="
    echoVerbose "| Run Php"
    echoVerbose "+====================================================="
    startPhpService
}

function startPhpService {
    if [[ -x /usr/sbin/php-fpm ]]; then
      echo "starting php-fpm process"
      /usr/sbin/php-fpm -D
    elif [[ -x /usr/sbin/php-fpm7 ]]; then
      echo "starting php-fpm process"
      /usr/sbin/php-fpm7 -D
    fi;
    startApacheService
}

# Display liveness status
function phpIsLive {
    genericIsLive
}

# Display readyness status
function phpIsReady {
    apacheIsReady
}
