#!/bin/bash
source /var/lib/sx/sxlib-apache

# Display php information
function phpInformation {
    apacheInformation $1 
    echo $1 "php       : $(php --version | head -1)" 
}

# function executed when pre-deploy hook is called
function phpPreDeploy {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running PRE-DEPLOY HOOK"
    echo "| "
    phpInformation "| "
    echo "+====================================================="
    echo "Create log directory $LOG_PATH"
    touch $LOG_PATH/access.log
    chown 1001:0 -R $LOG_PATH
    chmod g=u -R $LOG_PATH
}

# function executed when post-deploy hook is called
function phpPostDeploy {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running POST-DEPLOY HOOK"
    echo "| "
    phpInformation "| "
    echo "+====================================================="
}

# function executed when pre-build hook is called
function phpPostBuild {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running POST-BUILD HOOK"
    echo "| "
    phpInformation "| "
    echo "+====================================================="
}

# function executed when assemble hook is called
function phpAssemble {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running ASSEMBLE"
    echo "| "
    phpInformation "| "
    echo "+====================================================="
    echo "Fixing perm on /tmp/src"
    chown 1001:0 -R /tmp/src
    chmod g=u -R /tmp/src
    echo "Copy source from /tmp/src > $APP_PATH"
    cp -R /tmp/src/* $APP_PATH/
    rm -rf /tmp/src
}

# function executed on container startup
function phpRun {
    echo "+====================================================="
    echo "| Container $HOSTNAME is RUNNING"
    echo "| "
    phpInformation "| "
    echo "+====================================================="
    startApacheService
}
