---
kind: ImageStreamList
apiVersion: v1
metadata: 
  name: startx-vdi
  annotations:
    openshift.io/generated-by: STARTX
  labels:
    provider: startx
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: startx-chrome
    annotations:
      openshift.io/display-name: Startx Chrome Browser (S2I)
      openshift.io/generated-by: STARTX
    labels:
      provider: startx
  spec:
    tags:
    - name: fc27
      annotations:
        openshift.io/display-name: VDI Chrome Browser (Fedora 27)
        description: Container-based desktop Chrome browser for remote internet browsing  under
          Fedora 27
        iconClass: icon-aerogear
        tags: builder,startx,fedora,chrome,vnc
        supports: vnc
        version: fc27
        sampleRepo: https://github.com/startxfr/docker-images-example-chrome.git
      from:
        kind: DockerImage
        name: startx/vdi-chrome:fc27
    - name: fc28
      annotations:
        openshift.io/display-name: VDI Chrome Browser (Fedora 28)
        description: Container-based desktop Chrome browser for remote internet browsing  under
          Fedora 28
        iconClass: icon-aerogear
        tags: builder,startx,fedora,chrome,vnc
        supports: vnc
        version: fc28
        sampleRepo: https://github.com/startxfr/docker-images-example-chrome.git
      from:
        kind: DockerImage
        name: startx/vdi-chrome:fc28
    - name: fc29
      annotations:
        openshift.io/display-name: VDI Chrome Browser (Fedora 29)
        description: Container-based desktop Chrome browser for remote internet browsing  under
          Fedora 29
        iconClass: icon-aerogear
        tags: builder,startx,fedora,chrome,vnc
        supports: vnc
        version: fc29
        sampleRepo: https://github.com/startxfr/docker-images-example-chrome.git
      from:
        kind: DockerImage
        name: startx/vdi-chrome:fc29
    - name: fc30
      annotations:
        openshift.io/display-name: VDI Chrome Browser (Fedora 30)
        description: Container-based desktop Chrome browser for remote internet browsing  under
          Fedora 30
        iconClass: icon-aerogear
        tags: builder,startx,fedora,chrome,vnc
        supports: vnc
        version: fc30
        sampleRepo: https://github.com/startxfr/docker-images-example-chrome.git
      from:
        kind: DockerImage
        name: startx/vdi-chrome:fc30
    - name: fc31
      annotations:
        openshift.io/display-name: VDI Chrome Browser (Fedora 31)
        description: Container-based desktop Chrome browser for remote internet browsing  under
          Fedora 31
        iconClass: icon-aerogear
        tags: builder,startx,fedora,chrome,vnc
        supports: vnc
        version: fc31
        sampleRepo: https://github.com/startxfr/docker-images-example-chrome.git
      from:
        kind: DockerImage
        name: startx/vdi-chrome:fc31
    - name: latest
      annotations:
        openshift.io/display-name: VDI Chrome Browser (Fedora rawhide)
        description: Container-based desktop Chrome browser for remote internet browsing  under
          Fedora rawhide
        iconClass: icon-aerogear
        tags: builder,startx,fedora,chrome,vnc
        supports: vnc
        version: rawhide
        sampleRepo: https://github.com/startxfr/docker-images-example-chrome.git
      from:
        kind: DockerImage
        name: startx/vdi-chrome:latest
    - name: centos7
      annotations:
        openshift.io/display-name: VDI Chrome Browser (Centos 7)
        description: Container-based desktop Chrome browser for remote internet browsing  under
          Centos 7
        iconClass: icon-aerogear
        tags: builder,startx,centos,chrome,vnc
        supports: vnc
        version: '7'
        sampleRepo: https://github.com/startxfr/docker-images-example-chrome.git
      from:
        kind: DockerImage
        name: startx/vdi-chrome:centos7
    - name: alpine3
      annotations:
        openshift.io/display-name: VDI Chrome Browser (Alpine 3)
        description: Container-based desktop Chrome browser for remote internet browsing  under
          Alpine 3
        iconClass: icon-aerogear
        tags: builder,startx,alpine,chrome,vnc
        supports: vnc
        version: '3'
        sampleRepo: https://github.com/startxfr/docker-images-example-chrome.git
      from:
        kind: DockerImage
        name: startx/vdi-chrome:alpine3
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: startx-firefox
    annotations:
      openshift.io/display-name: Startx Firefox Browser (S2I)
      openshift.io/generated-by: STARTX
    labels:
      provider: startx
  spec:
    tags:
    - name: fc27
      annotations:
        openshift.io/display-name: VDI Firefox Browser (Fedora 27)
        description: Container-based desktop Firefox browser for remote internet browsing  under
          Fedora 27
        iconClass: icon-aerogear
        tags: builder,startx,fedora,firefox,vnc
        supports: vnc
        version: fc27
        sampleRepo: https://github.com/startxfr/docker-images-example-firefox.git
      from:
        kind: DockerImage
        name: startx/vdi-firefox:fc27
    - name: fc28
      annotations:
        openshift.io/display-name: VDI Firefox Browser (Fedora 28)
        description: Container-based desktop Firefox browser for remote internet browsing  under
          Fedora 28
        iconClass: icon-aerogear
        tags: builder,startx,fedora,firefox,vnc
        supports: vnc
        version: fc28
        sampleRepo: https://github.com/startxfr/docker-images-example-firefox.git
      from:
        kind: DockerImage
        name: startx/vdi-firefox:fc28
    - name: fc29
      annotations:
        openshift.io/display-name: VDI Firefox Browser (Fedora 29)
        description: Container-based desktop Firefox browser for remote internet browsing  under
          Fedora 29
        iconClass: icon-aerogear
        tags: builder,startx,fedora,firefox,vnc
        supports: vnc
        version: fc29
        sampleRepo: https://github.com/startxfr/docker-images-example-firefox.git
      from:
        kind: DockerImage
        name: startx/vdi-firefox:fc29
    - name: fc31
      annotations:
        openshift.io/display-name: VDI Firefox Browser (Fedora 31)
        description: Container-based desktop Firefox browser for remote internet browsing  under
          Fedora 31
        iconClass: icon-aerogear
        tags: builder,startx,fedora,firefox,vnc
        supports: vnc
        version: fc31
        sampleRepo: https://github.com/startxfr/docker-images-example-firefox.git
      from:
        kind: DockerImage
        name: startx/vdi-firefox:fc31
    - name: latest
      annotations:
        openshift.io/display-name: VDI Firefox Browser (Fedora rawhide)
        description: Container-based desktop Firefox browser for remote internet browsing  under
          Fedora rawhide
        iconClass: icon-aerogear
        tags: builder,startx,fedora,firefox,vnc
        supports: vnc
        version: rawhide
        sampleRepo: https://github.com/startxfr/docker-images-example-firefox.git
      from:
        kind: DockerImage
        name: startx/vdi-firefox:latest
    - name: centos7
      annotations:
        openshift.io/display-name: VDI Firefox Browser (Centos 7)
        description: Container-based desktop Firefox browser for remote internet browsing  under
          Centos 7
        iconClass: icon-aerogear
        tags: builder,startx,centos,firefox,vnc
        supports: vnc
        version: '7'
        sampleRepo: https://github.com/startxfr/docker-images-example-firefox.git
      from:
        kind: DockerImage
        name: startx/vdi-firefox:centos7
    - name: alpine3
      annotations:
        openshift.io/display-name: VDI Firefox Browser (Alpine 3)
        description: Container-based desktop Firefox browser for remote internet browsing  under
          Alpine 3
        iconClass: icon-aerogear
        tags: builder,startx,alpine,firefox,vnc
        supports: vnc
        version: '3'
        sampleRepo: https://github.com/startxfr/docker-images-example-firefox.git
      from:
        kind: DockerImage
        name: startx/vdi-firefox:alpine3
