chrome:
  build: ./
  container_name: "vdi-chrome"
  ports:
    - "9267:5900"
  privileged: true
  environment:
    SX_CHROME_SCREEN_RES_X: "1600x900x24"
    SX_CHROME_SCREEN_RES_CHROME: "1600,900"
    SX_VERBOSE: 'true'
  volumes:
    - "/dev/shm:/dev/shm"
#    - "/mnt/chrome:/home/chrome:Z"
#  command:
#    - "/bin/sx-chrome"
#    - "run"
