---
kind: Template
apiVersion: v1
metadata:
  name: startx-chrome-deploy-template
  annotations:
    openshift.io/display-name: Startx Chrome browser (fedora)
    description: Chrome browser for simple web application running under Fedora
    iconClass: icon-aerogear
    tags: startx,os,fedora,chrome
    openshift.io/long-description:
      This template provides an Chrome browser in a fedora
      container. Ready to use in openshift with a simple deployement config, or as
      a s2i builder for building personalized browser container. For more information
      about using this image, including OpenShift considerations, see https://gitlab.com/startx1/containers/blob/master/README.md.
    openshift.io/provider-display-name: STARTX
    openshift.io/documentation-url: https://gitlab.com/startx1/containers/blob/master/README.md
    openshift.io/support-url: https://gitlab.com/startx1/containers/issues/new
message:
  "The following container have been created in your project: ${APP_NAME} and
  you can use openshift console to log into."
labels:
  template: startx-chrome-deploy-template
  provider: startx
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${APP_NAME}"
      annotations:
        openshift.io/display-name: Startx Browser
        openshift.io/generated-by: STARTX
      labels:
        app: "${APP_NAME}"
        provider: startx
        template: startx-chrome-deploy-template
    spec:
      tags:
        - name: latest
          annotations:
            openshift.io/display-name: Startx Browser (Fedora rawhide)
            description:
              Container-based desktop Chrome browser for remote internet browsing  under
              Fedora rawhide
            iconClass: icon-aerogear
            tags: builder,startx,fedora,chrome,vnc
            supports: vnc
            version: rawhide
            sampleRepo: https://gitlab.com/startx1/containers-example-chrome.git
          from:
            kind: DockerImage
            name: startx/vdi-chrome:latest
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${APP_NAME}"
      labels:
        app: "${APP_NAME}"
        provider: startx
        template: startx-chrome-deploy-template
      annotations:
        openshift.io/generated-by: STARTX
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 90
          maxUnavailable: 25%
          maxSurge: 25%
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${APP_NAME}"
            from:
              kind: ImageStreamTag
              name: "${APP_NAME}:latest"
        - type: ConfigChange
      postCommit:
        script: "/bin/sx-chrome info"
      replicas: 1
      test: false
      selector:
        app: "${APP_NAME}"
        deploymentconfig: "${APP_NAME}"
      template:
        metadata:
          labels:
            app: "${APP_NAME}"
            provider: startx
            template: startx-chrome-deploy-template
            deploymentconfig: "${APP_NAME}"
          annotations:
            openshift.io/generated-by: STARTX
        spec:
          containers:
            - name: "${APP_NAME}"
              image: " "
              env:
                - name: SX_VERBOSE
                  value: "true"
              command:
                - "/bin/sx-chrome"
              args:
                - run
              livenessProbe:
                exec:
                  command:
                    - "/bin/sx-chrome"
                    - isLive
                initialDelaySeconds: 4
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                exec:
                  command:
                    - "/bin/sx-chrome"
                    - isReady
                initialDelaySeconds: 4
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              resources:
                limits:
                  cpu: 12000m
                  memory: 2048Mi
                requests:
                  cpu: 200m
                  memory: 512Mi
              terminationMessagePath: "/dev/termination-log"
              imagePullPolicy: Always
              volumeMounts:
                - name: "${APP_NAME}-shm"
                  mountPath: "/dev/shm"
                - name: "${APP_NAME}-data"
                  mountPath: "/home/chrome"
          volumes:
            - name: "${APP_NAME}-shm"
              hostPath:
                path: "/dev/shm"
            - name: "${APP_NAME}-data"
              emptyDir:
                medium: ""
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
  - kind: Route
    apiVersion: v1
    metadata:
      name: "${APP_NAME}"
      labels:
        app: "${APP_NAME}"
        provider: startx
        template: startx-chrome-deploy-template
      annotations:
        openshift.io/generated-by: STARTX
    spec:
      to:
        kind: Service
        name: "${APP_NAME}"
        weight: 100
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APP_NAME}"
      labels:
        app: "${APP_NAME}"
        provider: startx
        template: startx-chrome-deploy-template
      annotations:
        openshift.io/generated-by: STARTX
    spec:
      ports:
        - protocol: TCP
          port: 5900
          targetPort: 5900
      selector:
        app: "${APP_NAME}"
        deploymentconfig: "${APP_NAME}"
      type: ClusterIP
      sessionAffinity: None
parameters:
  - name: APP_NAME
    displayName: Application name
    description: The name of the created application
    value: chrome
    required: true
  - name: RUN_ACTION
    displayName: Main action to perfom
    description:
      Action to perform for this running Pod. Should be one of build, post-build,
      pre-deploy, post-deploy, run, isLive, isReady, usage, usageS2i, daemon, info,
      version. See documentation for action list.
    value: run
    required: true
