memcache:
  build: ./
  container_name: "fc32-service-memcache"
  mem_limit: 2g
  memswap_limit: 3g
  cpu_shares: 2
  restart: "on-failure:2"
  privileged: true
  ports:
    - "9278:11211"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "memcache"
#  volumes:
#    - "/tmp/container/memcache/logs:/logs:z"
#  command:
#     - "/bin/sx-memcache"
#     - "run"
