server:
  build: ./
  container_name: "centos6-service-memcache"
  mem_limit: 2g
  memswap_limit: 3g
  cpu_shares: 2
  restart: "on-failure:2"
  privileged: true
  ports:
    - "9271:11211"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "memcache"
    CONTAINER_INSTANCE: "centos6-service-memcache"
  volumes:
    - "/tmp/container-centos6/logs/memcache:/logs"
