memcache:
  build: ./
  container_name: "fc30-service-memcache"
  mem_limit: 2g
  memswap_limit: 3g
  cpu_shares: 2
  restart: "on-failure:2"
  privileged: true
  ports:
    - "9278:11211"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "memcache"
    CONTAINER_INSTANCE: "fc30-service-memcache"
  volumes:
    - "/tmp/container-fc30/logs/memcache:/logs:z
