#!/bin/bash

function check_memcache_environment {
    if [ ! -v LOG_PATH ]; then
        LOG_PATH="/logs"
        export LOG_PATH
    fi
}

function memcacheInformation {
    displayInformation $1
    echo $1 "version   : $SX_VERSION"
    echo $1 "memcache  : $(memcached -h | head -1)"
    echo $1 "log path  : $LOG_PATH"
}

function displayMemcacheRunInformation {
    memcacheInformation $1
    echo $1 "admin     : root:$MYSQL_ROOT_PASSWORD"
    echo $1 "user      : $MYSQL_USER:$MYSQL_PASSWORD"
    echo $1 "database  : $MYSQL_DATABASE"
}

function memcachePreDeploy {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running PRE-DEPLOY HOOK"
    echo "| "
    memcacheInformation "| "
    echo "+====================================================="
}

function memcachePostDeploy {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running POST-DEPLOY HOOK"
    echo "| "
    memcacheInformation "| "
    echo "+====================================================="
}

function memcachePostBuild {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running POST-BUILD HOOK"
    echo "| "
    memcacheInformation "| "
    echo "+====================================================="
}

function memcacheAssemble {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running ASSEMBLE"
    echo "| "
    memcacheInformation "| "
    echo "+====================================================="
    echo "Fixing perm on /tmp/src"
    chown 1001:0 -R /tmp/src
    chmod g=u -R /tmp/src
    echo "Copy sql scripts from /tmp/src > $LOADSQL_PATH"
    cp -R /tmp/src/*.sql $LOADSQL_PATH/
    rm -rf /tmp/src
    init_service_memcache
}

function memcacheRun {
    echo "+====================================================="
    echo "| Container $HOSTNAME is RUNNING"
    echo "| "
    displayMemcacheRunInformation "| "
    echo "+====================================================="
    start_service_memcache
}

function stop_memcache_handler {
    killall memcached
    echo "+====================================================="
    echo "| Container $HOSTNAME is now STOPPED"
    echo "+====================================================="
    exit 143; # 128 + 15 -- SIGTERM
}

# Start the memcache server as a deamon and execute it inside 
# the running shell
function start_service_memcache {
    trap 'kill ${!}; stop_memcache_handler' SIGHUP SIGINT SIGQUIT SIGTERM SIGKILL SIGSTOP SIGCONT
    exec memcached -u daemon -v
}
