---
kind: ImageStreamList
apiVersion: v1
metadata: 
  name: startx-couchbase
  annotations:
    openshift.io/generated-by: STARTX
  labels:
    provider: startx
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: startx-couchbase
    annotations:
      openshift.io/display-name: Startx Couchbase Database (S2I)
      openshift.io/generated-by: STARTX
    labels:
      base-image: startx-couchbase
      provider: startx
  spec:
    tags:
    - name: fc27
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Fedora 27)
        description: Couchbase server builder for NoSQL database running under Fedora
          27
        iconClass: icon-mysql-database
        tags: builder,startx,fedora,couchbase,database
        supports: db
        version: fc27
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:fc27
    - name: fc28
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Fedora 28)
        description: Couchbase server builder for NoSQL database running under Fedora
          28
        iconClass: icon-mysql-database
        tags: builder,startx,fedora,couchbase,database
        supports: db
        version: fc28
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:fc28
    - name: fc29
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Fedora 29)
        description: Couchbase server builder for NoSQL database running under Fedora
          29
        iconClass: icon-mysql-database
        tags: builder,startx,fedora,couchbase,database
        supports: db
        version: fc29
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:fc29
    - name: fc30
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Fedora 30)
        description: Couchbase server builder for NoSQL database running under Fedora
          30
        iconClass: icon-mysql-database
        tags: builder,startx,fedora,couchbase,database
        supports: db
        version: fc30
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:fc30
    - name: fc31
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Fedora 31)
        description: Couchbase server builder for NoSQL database running under Fedora
          31
        iconClass: icon-mysql-database
        tags: builder,startx,fedora,couchbase,database
        supports: db
        version: fc31
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:fc31
    - name: latest
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Fedora rawhide)
        description: Couchbase server builder for NoSQL database running under Fedora
          rawhide
        iconClass: icon-mysql-database
        tags: builder,startx,fedora,couchbase,database
        supports: db
        version: rawhide
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:latest
    - name: centos7
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Centos 7)
        description: Couchbase server builder for NoSQL database running under Centos
          7
        iconClass: icon-mysql-database
        tags: builder,startx,centos,couchbase,database
        supports: db
        version: '7'
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:centos7
    - name: centos6
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Centos 6)
        description: Couchbase server builder for NoSQL database running under Centos
          6
        iconClass: icon-mysql-database
        tags: builder,startx,centos,couchbase,database
        supports: db
        version: '6'
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:centos6
    - name: alpine3
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Alpine 3)
        description: Couchbase server builder for NoSQL database running under Alpine
          3
        iconClass: icon-mysql-database
        tags: builder,startx,alpine,couchbase,database
        supports: db
        version: '3'
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:alpine3
