---
kind: Template
apiVersion: v1
metadata:
  name: startx-couchbase-build-template
  annotations:
    openshift.io/display-name: Couchbase database Server (ephemeral build & deploy workflow)
    description: Build and deployement workflow of a nosql database using ephemeral storage
      for logs records. Use couchbase with various underlying linux distribution. See 
      https://hub.docker.com/r/startx/sv-couchbase
    iconClass: icon-couchbase
    tags: startx,os,fedora,couchbase,nosql
    openshift.io/provider-display-name: STARTX
    openshift.io/documentation-url: https://hub.docker.com/r/startx/sv-couchbase
    openshift.io/support-url: https://github.com/startxfr/docker-images/issues/new
message: |-
  Your database ${APP_NAME} is building and will be soon deployed.
  Monitor the deployement for database availability and
  Follow created route to browse running application

  Source      : ${SOURCE_BRANCH}@${SOURCE_GIT}
  Database    : ${APP_NAME}
  Stage       : ${APP_STAGE}
  Builder     : ${BUILDER_TAG}
labels:
  template: startx-couchbase-build-template
  provider: startx 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: startx-couchbase
    annotations:
      openshift.io/display-name: Startx Couchbase Database (S2I)
      openshift.io/generated-by: STARTX
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
  spec:
    tags:
    - name: fc27
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Fedora 27)
        description: Couchbase server builder for NoSQL database running under Fedora
          27
        iconClass: icon-mysql-database
        tags: builder,startx,fedora,couchbase,database
        supports: db
        version: fc27
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:fc27
    - name: fc28
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Fedora 28)
        description: Couchbase server builder for NoSQL database running under Fedora
          28
        iconClass: icon-mysql-database
        tags: builder,startx,fedora,couchbase,database
        supports: db
        version: fc28
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:fc28
    - name: fc29
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Fedora 29)
        description: Couchbase server builder for NoSQL database running under Fedora
          29
        iconClass: icon-mysql-database
        tags: builder,startx,fedora,couchbase,database
        supports: db
        version: fc29
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:fc29
    - name: fc30
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Fedora 30)
        description: Couchbase server builder for NoSQL database running under Fedora
          30
        iconClass: icon-mysql-database
        tags: builder,startx,fedora,couchbase,database
        supports: db
        version: fc30
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:fc30
    - name: fc31
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Fedora 31)
        description: Couchbase server builder for NoSQL database running under Fedora
          31
        iconClass: icon-mysql-database
        tags: builder,startx,fedora,couchbase,database
        supports: db
        version: fc31
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:fc31
    - name: latest
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Fedora rawhide)
        description: Couchbase server builder for NoSQL database running under Fedora
          rawhide
        iconClass: icon-mysql-database
        tags: builder,startx,fedora,couchbase,database
        supports: db
        version: rawhide
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:latest
    - name: centos8
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Centos 8)
        description: Couchbase server builder for NoSQL database running under Centos
          8
        iconClass: icon-mysql-database
        tags: builder,startx,centos,couchbase,database
        supports: db
        version: '8'
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:centos8
    - name: centos7
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Centos 7)
        description: Couchbase server builder for NoSQL database running under Centos
          7
        iconClass: icon-mysql-database
        tags: builder,startx,centos,couchbase,database
        supports: db
        version: '7'
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:centos7
    - name: centos6
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Centos 6)
        description: Couchbase server builder for NoSQL database running under Centos
          6
        iconClass: icon-mysql-database
        tags: builder,startx,centos,couchbase,database
        supports: db
        version: '6'
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:centos6
    - name: alpine3
      annotations:
        openshift.io/display-name: S2I Couchbase Database (Alpine 3)
        description: Couchbase server builder for NoSQL database running under Alpine
          3
        iconClass: icon-mysql-database
        tags: builder,startx,alpine,couchbase,database
        supports: db
        version: '3'
        sampleRepo: https://github.com/startxfr/docker-images-example-couchbase.git
      from:
        kind: DockerImage
        name: startx/sv-couchbase:alpine3
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    annotations:
      openshift.io/display-name: Application ${APP_NAME}
      openshift.io/generated-by: STARTX
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/display-name: Application ${APP_NAME}
        description: Base image for the application ${APP_NAME}
        iconClass: icon-mysql-database
        tags: startx,fedora,couchbase,database,application,${APP_NAME}
        supports: db
        version: rawhide
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
  stringData:
    COUCHBASE_PASSWORD: "${COUCHBASE_PASSWORD}"
    COUCHBASE_USER: "${COUCHBASE_USER}"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 120
        maxUnavailable: 25%
        maxSurge: 25%
        pre:
          failurePolicy: Abort
          execNewPod:
            command:
            - "/bin/sx-couchbase"
            - pre-deploy
            env:
            - name: SX_VERBOSE
              value: 'true'
            - name: SX_DEBUG
              value: 'true'
            containerName: "${APP_NAME}"
        post:
          failurePolicy: Abort
          execNewPod:
            command:
            - "/bin/sx-couchbase"
            - post-deploy
            env:
            - name: SX_VERBOSE
              value: 'true'
            - name: SX_DEBUG
              value: 'true'
            containerName: "${APP_NAME}"
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}"
        from:
          kind: ImageStreamTag
          name: "${APP_NAME}:latest"
    - type: ConfigChange
    postCommit:
      script: "/bin/sx-couchbase info"
    replicas: 1
    test: false
    selector:
      app: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    template:
      metadata:
        labels:
          app: "${APP_NAME}"
          type: "${APP_STAGE}"
          provider: startx
          template: startx-couchbase-build-template
          deploymentconfig: "${APP_NAME}"
        annotations:
          openshift.io/generated-by: STARTX
      spec:
        containers:
        - name: "${APP_NAME}"
          image: " "
          env:
          - name: COUCHBASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${APP_NAME}"
                key: COUCHBASE_PASSWORD
          - name: COUCHBASE_USER
            valueFrom:
              secretKeyRef:
                name: "${APP_NAME}"
                key: COUCHBASE_USER
          - name: COUCHBASE_BUCKETS
            value: "${COUCHBASE_BUCKETS}"
          command:
          - "/bin/sx-couchbase"
          args:
          - run
          ports:
          - containerPort: 8091
            protocol: TCP
          - protocol: TCP
            containerPort: 8092
          - protocol: TCP
            containerPort: 8093
          - protocol: TCP
            containerPort: 8094
          - protocol: TCP
            containerPort: 11207
          - protocol: TCP
            containerPort: 11210
          - protocol: TCP
            containerPort: 11211
          - protocol: TCP
            containerPort: 18091
          - protocol: TCP
            containerPort: 18092
          - protocol: TCP
            containerPort: 18093
          - protocol: TCP
            containerPort: 18094
          resources:
            limits:
              cpu: 12000m
              memory: "${MEMORY_LIMIT}"
            requests:
              cpu: 200m
              memory: "${MEMORY_LIMIT}"
          volumeMounts:
          - name: "${APP_NAME}-data"
            mountPath: "/opt/couchbase/var"
          livenessProbe:
            exec:
              command:
              - "/bin/sx-couchbase"
              - isLive
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - "/bin/sx-couchbase"
              - isReady
            initialDelaySeconds: 2
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: Always
        volumes:
        - name: "${APP_NAME}-data"
          emptyDir:
            medium: ''
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
  status:
    observedGeneration: 2
    replicas: 1
    updatedReplicas: 1
    availableReplicas: 1
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    ports:
    - name: cluster-webapi
      protocol: TCP
      port: 8091
      targetPort: 8091
    - name: cluster-viewxdcr
      protocol: TCP
      port: 8092
      targetPort: 8092
    - name: cluster-query
      protocol: TCP
      port: 8093
      targetPort: 8093
    - name: cluster-fts
      protocol: TCP
      port: 8094
      targetPort: 8094
    - name: data-moxi-ssl
      protocol: TCP
      port: 11207
      targetPort: 11207
    - name: data-moxi
      protocol: TCP
      port: 11210
      targetPort: 11210
    - name: data-legacy
      protocol: TCP
      port: 11211
      targetPort: 11211
    - name: cluster-webapi-ssl
      protocol: TCP
      port: 18091
      targetPort: 18091
    - name: cluster-viewxdcr-ssl
      protocol: TCP
      port: 18092
      targetPort: 18092
    - name: cluster-query-ssl
      protocol: TCP
      port: 18093
      targetPort: 18093
    - name: cluster-fts-ssl
      protocol: TCP
      port: 18094
      targetPort: 18094
    selector:
      app: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    triggers:
    - type: GitHub
      github:
        secret: "${WEBHOOK_TOKEN}_${APP_NAME}"
    - type: Generic
      generic:
        secret: "${WEBHOOK_TOKEN}_${APP_NAME}"
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
    runPolicy: SerialLatestOnly
    source:
      type: Git
      git:
        uri: "${SOURCE_GIT}"
        ref: "${SOURCE_BRANCH}"
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: startx-couchbase:${BUILDER_TAG}
        env:
        - name: SX_VERBOSE
          value: 'true'
    output:
      to:
        kind: ImageStreamTag
        name: "${APP_NAME}:latest"
    postCommit:
      command:
      - "/bin/sx-couchbase"
      - post-build
  status:
    lastVersion: 0
parameters:
- name: APP_NAME
  displayName: Application name
  description: The name of the created application
  value: couchbase
  required: true
- name: APP_STAGE
  displayName: Application stage
  description: "Stage of the application deployed (ex: dev, test, prod, example, demo, poc, ...)"
  value: example
  required: true
- name: SOURCE_GIT
  displayName: Source repository
  description: URL to the source code to use during build process
  value: https://github.com/startxfr/docker-images-example-couchbase.git
  required: true
- name: SOURCE_BRANCH
  displayName: Source branch
  description: Name of the default branch
  value: master
  required: true
- name: BUILDER_TAG
  displayName: Builder image stage
  description: "Image tag of the startx couchbase builder image used. Could be : latest, dev, test, preprod, prod - rawhide, fc31, fc30, fc29, fc28 - alpine3 - centos8, centos7, centos6)"
  value: latest
- name: WEBHOOK_TOKEN
  displayName: Webhook token
  description: Secret token to use for webhook to github or generic
  generate: expression
  from: "[a-zA-Z0-9]{24}"
  required: true
- name: COUCHBASE_USER
  displayName: Couchbase user
  description: Default user to create
  value: demo
  from: "[A-Z0-9]{8}"
  generate: expression
- name: COUCHBASE_PASSWORD
  displayName: Couchbase root password
  description: The couchbase admin password to use. Generated if not provided
  from: "[A-Z0-9]{16}"
  generate: expression
- name: COUCHBASE_BUCKETS
  displayName: Couchbase bucket
  description: list of the default's bucket to create
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use. e.g. 512Mi, 2Gi.
  value: 2048Mi
  required: true
