#!/bin/bash
OS=`cat /etc/os-release | grep "PRETTY_NAME" | sed 's/PRETTY_NAME=//g' | sed 's/["]//g'`

export TERM=xterm
pid=0

function isDebug {
    if [ ! -z "$SX_DEBUG" ]; then
        if [[ $SX_DEBUG == *"true"* ]]; then
            echo "true";
            return;
        fi 
    fi 
    echo "false";
}

function isVerbose {
    if [ ! -z "$SX_VERBOSE" ]; then
        if [[ $SX_VERBOSE == *"true"* ]]; then
            echo "true";
            return;
        fi 
    fi 
    echo "false";
}


function genericPreDeploy {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running PRE-DEPLOY HOOK"
    if [ `isVerbose` == "true" ]; then
        echo "| "
        displayInformation "| "
    fi 
    echo "+====================================================="
    testAndRunSourceCodeScript "pre-deploy" 
}

function genericPostDeploy {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running POST-DEPLOY HOOK"
    if [ `isVerbose` == "true" ]; then
        echo "| "
        displayInformation "| "
    fi 
    echo "+====================================================="
    testAndRunSourceCodeScript "post-deploy" 
}

function genericPostBuild {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running POST-BUILD HOOK"
    if [ `isVerbose` == "true" ]; then
        echo "| "
        displayInformation "| "
    fi 
    echo "+====================================================="
    testAndRunSourceCodeScript "post-build" 
}

function genericAssemble {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running ASSEMBLE"
    if [ `isVerbose` == "true" ]; then
        echo "| "
        displayInformation "| "
    fi 
    echo "+====================================================="
    if [ `isVerbose` == "true" ]; then
        echo "Fixing perm on /tmp/src"
    fi 
    chown 1001:0 -R /tmp/src
    chmod g=u -R /tmp/src
    chmod ug+x -R /tmp/src/.sx/*
    if [ `isVerbose` == "true" ]; then
        echo "Copy source from /tmp/src > /tmp"
    fi 
    cp -R /tmp/src/* /tmp/
    if [ `isVerbose` == "true" ]; then
        echo "Remove source temp /tmp/src"
    fi 
    rm -rf /tmp/src
    testAndRunSourceCodeScript "assemble" 
}


function genericRun {
    echo "+====================================================="
    echo "| Container $HOSTNAME is RUNNING"
    if [ `isVerbose` == "true" ]; then
        echo "| "
        displayInformation "| "
    fi 
    echo "+====================================================="
    if [[ -r /tmp/.sx ]]; then
        if [ `isVerbose` == "true" ]; then
            echo "Found source code CI/CD scripts in .sx/"
        fi 
        if [[ -r /tmp/.sx/run ]]; then
            if [ `isVerbose` == "true" ]; then
                echo "Found source code run script"
            fi 
            if [[ -x /tmp/.sx/run ]]; then
                echo "Execute source code run script"
                exec /tmp/.sx/run
            else
                echo "Start default daemon (source code run is script not executable)"
                genericDaemon
            fi 
        else
            echo "Start default daemon (no source code run script)"
            genericDaemon
        fi 
    else
        genericDaemon
    fi 
}



#######################################
# Display general usage
#######################################
function genericUsage {
cat <<EOF
Basic OS container to execute arbitrary commands

Usage:
  docker run $SX_ID /bin/sx [command]

- General Commands:
  assemble         execute for building output image when using s2i 
  post-build       execute after building image
  pre-deploy       execute before the deployment begins (openshift).
  post-deploy      execute after the deployment strategy completes (openshift).
  run              execute the service on container startup
  health           return the service health
  usage            this message
  help             display information about this tools
  info             give information about the running container
  version          give the version of the running container
  daemon           execute the container as a daemon (keep alive)

EOF
exit 0;
}


#######################################
# Display S2I usage
#######################################
function genericUsageS2I {
cat <<EOF
Startx builder container to use with s2i or openshift

Usage:
  s2i $SX_ID <code_repo_url> ≤image_name>

Code repository must have a `run` script who will be executed on container startup

EOF
exit 0;
}



#######################################
# Display general welcome message
#######################################
function genericWelcome {
cat <<EOF
Welcome to the $SX_ID base image. If you see this message, you have
probably run this container without arguments. See usage for more informations.

docker run $SX_ID /bin/sx usage

EOF
exit 0;
}

#######################################
# Display information
#######################################
function displayInformation {
echo $1 "type      : $SX_TYPE"
echo $1 "service   : $SX_SERVICE"
echo $1 "image     : $SX_ID:$SX_VERSION"
echo $1 "name      : $SX_NAME"
echo $1 "OS        : $OS"
echo $1 "container : $HOSTNAME"
}

#######################################
# Display information
#######################################
function genericAllInformation {
displayInformation
if [ `isDebug` == "true" ]; then
    env
fi 
}

#######################################
# Display version
#######################################
function genericVersion {
echo $SXDBTOOLS_VERSION
exit 0;
}

#######################################
# Display health
#######################################
function genericHealth {
echo "OK"
exit 0;
}

#######################################
# Display daemon
#######################################
function genericDaemon {
    while true; do
        echo "$HOSTNAME is alive and running $SX_ID:$SX_VERSION"
        sleep 10
    done
}

function testAndRunSourceCodeScript {
    if [[ -r /tmp/.sx ]]; then
        if [ `isVerbose` == "true" ]; then
            echo "Found source code CI/CD scripts in .sx/"
        fi 
        if [[ -r /tmp/.sx/$1 ]]; then
            if [ `isVerbose` == "true" ]; then
                echo "Found source code $1 script"
            fi 
            if [[ -x /tmp/.sx/$1 ]]; then
                echo "Execute source code $1 script"
                . /tmp/.sx/$1
            else
                echo "WARN: source code $1 script is not executable"
            fi 
        else
            if [ `isVerbose` == "true" ]; then
                echo "No source code $1 script"
            fi 
        fi 
    else
        if [ `isVerbose` == "true" ]; then
            echo "no source code .sx directory"
        fi 
    fi 
}