#!/bin/bash
source /var/lib/sx/sx

function check_mariadb_environment {
    if [ ! -v DATA_PATH ]; then
        DATA_PATH="/data"
        export DATA_PATH
    fi
    if [ ! -v LOG_PATH ]; then
        LOG_PATH="/logs"
        export LOG_PATH
    fi
}

function mysqlInformation {
    displayInformation $1
    echoVerbose $1 "version   : $SX_VERSION"
    echoVerbose $1 "engine    : $(mysql -V | head -1)"
    echoVerbose $1 "sql path  : $LOADSQL_PATH"
    echoVerbose $1 "log path  : $LOG_PATH"
    echoVerbose $1 "data path : $DATA_PATH"
}

function displayMysqlRunInformation {
    mysqlInformation $1
    echoVerbose $1 "admin     : root:$MYSQL_ROOT_PASSWORD"
    echo $1 "user      : $MYSQL_USER:$MYSQL_PASSWORD"
    echo $1 "database  : $MYSQL_DATABASE"
}

function mysqlPreDeploy {
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME  running PRE-DEPLOY HOOK"
    echoVerbose "| "
    mysqlInformation "| "
    echoVerbose "+====================================================="
    testAndRunSourceCodeScript "pre-deploy" 
}

function mysqlPostDeploy {
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME  running POST-DEPLOY HOOK"
    echoVerbose "| "
    mysqlInformation "| "
    echoVerbose "+====================================================="
    testAndRunSourceCodeScript "post-deploy" 
}

function mysqlPostBuild {
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME  running POST-BUILD HOOK"
    echoVerbose "| "
    mysqlInformation "| "
    echoVerbose "+====================================================="
    testAndRunSourceCodeScript "post-build" 
}

function mysqlAssemble {
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME  running ASSEMBLE"
    echoVerbose "| "
    mysqlInformation "| "
    echoVerbose "+====================================================="
    if [[ -d $S2I_DEST ]]; then
        echoVerbose "Fixing perm on $S2I_DEST"
        chmod g=u -R $S2I_DEST
        echoVerbose "Copy sql scripts from $S2I_DEST > $LOADSQL_PATH"
        cp -R $S2I_DEST/*.sql $LOADSQL_PATH/
        moveSourceCode $S2I_DEST $APP_PATH
    fi
    testAndRunSourceCodeScript "assemble" 
    init_service_mariadb
}

function mysqlRun {
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME is RUNNING"
    echoVerbose "| "
    mysqlInformation "| "
    echoVerbose "+====================================================="
    startMariadbService
}

# Display liveness status
function mysqlIsLive {
    genericIsLive
}

# Display readyness status
function mysqlIsReady {
    mysql -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'  || exit 1;
}


# Init the mariadb server
function init_service_mariadb {
    begin_config
    end_config
}

# Begin configuration before starting daemonized process
# and start generating host keys
function begin_config {
    echoVerbose "=> BEGIN MARIADB CONFIGURATION"
    if [[ ! -d $DATA_PATH ]]; then
        echoVerbose "data directory $DATA_PATH not found"
        mkdir -p $DATA_PATH; 
        mkdir -p $DATA_PATH/store; 
        chmod 0774 $DATA_PATH;
        echoVerbose "data directory $DATA_PATH CREATED"
    else 
        echoVerbose "data directory $DATA_PATH EXIST"
    fi
    if [[ ! -d $LOG_PATH ]]; then
        echoVerbose "log directory $LOG_PATH not found"
        mkdir -p $LOG_PATH; 
        chmod 0774 $LOG_PATH;
        echoVerbose "log directory $LOG_PATH CREATED"
    else 
        echoVerbose "log directory $LOG_PATH EXIST"
    fi
    if [[ -d $LOADSQL_PATH ]]; then
        echoVerbose "sql directory $LOADSQL_PATH EXIST"
        chmod 0774 $LOADSQL_PATH; 
    fi
    echo "" >> $MY_CONF
    echo "[mysqld]" >> $MY_CONF
    echo "socket=/var/lib/mysql/mysql.sock" >> $MY_CONF
    echo "pid-file=/var/run/mysqld/mysqld.pid" >> $MY_CONF
    echo "datadir=$DATA_PATH" >> $MY_CONF
    echo "log-error=$LOG_PATH/mysqld.log" >> $MY_CONF
    echo "" >> $MY_CONF
    echo "[mariadb]" >> $MY_CONF
    echo "pid-file=/var/run/mariadb/mariadb.pid" >> $MY_CONF
    echo "datadir=$DATA_PATH" >> $MY_CONF
    echo "log-error=$LOG_PATH/mariadb.log" >> $MY_CONF
    echo "config file $MY_CONF updated"
    VOLUME_HOME=$DATA_PATH/mysql
    if [[ ! -d $VOLUME_HOME ]]; then
        echoVerbose "mariadb directory is empty or uninitialized"
        echo "Installing MariaDB in $DATA_PATH ..."
        mysql_install_db --defaults-file=$MY_CONF --datadir=$DATA_PATH > /dev/null 2>&1 
        echoVerbose "Installing MariaDB in $DATA_PATH is DONE !"
        config_startserver
        config_createadmin
        config_createuser
        config_createdatabase
        config_importsql
        config_stopserver
    else
        echoVerbose "mariadb directory is initialized"
        echoVerbose "Reusing MariaDB in $DATA_PATH ..."
    fi
}

function config_startserver {
    echoVerbose "start database for initial setup"
    mysqld_safe &
    mysql_pid=$!
    until mysqladmin ping >/dev/null 2>&1; do
        echo -n "."; sleep 0.2
    done
}

function config_stopserver {
    echoVerbose "stop database after initial setup"
    mysqladmin -u root -p$MYSQL_ROOT_PASSWORD shutdown
    wait $mysql_pid
}


function config_createadmin {
    PASS=${MYSQL_ROOT_PASSWORD:-$(pwgen -s 12 1)}
    _word=$( [ ${MYSQL_ROOT_PASSWORD} ] && echo "preset" || echo "random" )
    echoVerbose "Creating MariaDB admin user with ${_word} password"
    mysql -uroot -e "CREATE USER 'root'@'%' IDENTIFIED BY '$PASS'"
    mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION"
    MYSQL_ROOT_PASSWORD=$PASS
    export MYSQL_ROOT_PASSWORD=$PASS
    echo ""
    echo " +------------------------------------------------------"
    echo " | SUPERADMIN USER CREATED ! "
    echo " | You can now connect to this server using:"
    echo " | "
    echo " | user     : root"
    echo " | password : $MYSQL_ROOT_PASSWORD"
    echo " | "
    echo " | shell    : mysql -u root -p$MYSQL_ROOT_PASSWORD -h<host> -P<port>"
    echo " +------------------------------------------------------"
    echo ""
}

function config_createuser {
    if [[ -n "$MYSQL_USER" ]]; then
        echoVerbose "Creating MariaDB $MYSQL_USER user with preset password"
        PASS=${MYSQL_PASSWORD:-$(pwgen -s 12 1)}
        mysql -u root -p$MYSQL_ROOT_PASSWORD -h localhost -e "CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$PASS'"
        mysql -u root -p$MYSQL_ROOT_PASSWORD -h localhost -e "GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER'@'%' WITH GRANT OPTION"
        echo ""
        echo " +------------------------------------------------------"
        echo " | USER CREATED ! "
        echo " | You can now connect to this server using:"
        echo " | "
        echo " | user     : $MYSQL_USER"
        echo " | password : $PASS"
        echo " | "
        echo " | shell    : mysql -u $MYSQL_USER -p$PASS -h<host> -P<port>"
        echo " +------------------------------------------------------"
        echo ""
    else
        echoVerbose "No user created because no user defined in \$MYSQL_USER"
    fi
}

function config_createdatabase {
    if [[ -n "$MYSQL_DATABASE" ]]; then
        echoVerbose "processing database " $MYSQL_DATABASE
        if [[ ! -d $DIR_DB_DATA/$MYSQL_DATABASE ]]; then
            echoVerbose "database " $MYSQL_DATABASE " doesn't exist"
            mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE $MYSQL_DATABASE DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
            echo ""
            echo " +------------------------------------------------------"
            echo " | DATABASE CREATED ! "
            echo " | You can connect to this database using :"
            echo " | "
            echo " | database : $MYSQL_DATABASE"
            echo " | "
            echo " | shell    : mysql -u $MYSQL_USER -p$MYSQL_PASSWORD -h<host> -P<port> $MYSQL_DATABASE"
            echo " +------------------------------------------------------"
            echo ""
        else
            echoVerbose "database " $MYSQL_DATABASE " already exist"
        fi
    else
        echoVerbose "No database created because no database declared in \$MYSQL_DATABASE"
    fi
}

function config_importsql {
    if [[ -n "$LOADSQL_PATH" || -n "$MYSQL_DATABASE" ]]; then
        echoVerbose "\$LOADSQL_PATH is defined and set to " $LOADSQL_PATH
        if [[ -d $LOADSQL_PATH ]]; then
            if [ "$(ls -A $LOADSQL_PATH/schema-*.sql 2> /dev/null)" ]; then
                echo "Importing schema from $LOADSQL_PATH "
                SCHEMALIST=$(find $LOADSQL_PATH/schema-*.sql -type f -printf "%f\n")
                for SCHEMAFILE in $SCHEMALIST; do 
                    echo "SET NAMES utf8;"|cat - $LOADSQL_PATH/$SCHEMAFILE > /tmp/out && mv /tmp/out $LOADSQL_PATH/$SCHEMAFILE
                    echo -n "- schema " $SCHEMAFILE " ... "
                    mysql -u root -p$MYSQL_ROOT_PASSWORD -h localhost $MYSQL_DATABASE < $LOADSQL_PATH/$SCHEMAFILE
                    echo " IMPORTED"
                done
            else
                echoVerbose "No sql schema (schema-*.sql) found in $LOADSQL_PATH"
            fi
            if [ "$(ls -A $LOADSQL_PATH/data-*.sql 2> /dev/null)" ]; then
                echo "Importing data from $LOADSQL_PATH "
                DATALIST=$(find $LOADSQL_PATH/data-*.sql -type f -printf "%f\n")
                for DATAFILE in $DATALIST; do 
                    echo "SET NAMES utf8;"|cat - $LOADSQL_PATH/$DATAFILE > /tmp/out && mv /tmp/out $LOADSQL_PATH/$DATAFILE
                    echo -n "- data " $DATAFILE " ... "
                    mysql -u root -p$MYSQL_ROOT_PASSWORD -h localhost $MYSQL_DATABASE < $LOADSQL_PATH/$DATAFILE
                    echo " IMPORTED"
                done
            else
                echoVerbose "No sql data (data-*.sql) found in $LOADSQL_PATH"
            fi
        else
            echoVerbose "No sql scripts to load because $LOADSQL_PATH is not a directory"
        fi
    else
        echoVerbose "No sql scripts to load because no \$LOADSQL_PATH or \$MYSQL_DATABASE variables"
    fi
}


# End configuration process just before starting daemon
function end_config {
    echoVerbose "=> END MARIADB CONFIGURATION"
    touch $DATA_PATH/.sxIsInit
}

function stop_mariadb_handler {
    mysqladmin -u root -p$MYSQL_ROOT_PASSWORD shutdown
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME is now STOPPED"
    echoNotVerbose "container is now stopped"
    echoVerbose "| "
    mysqlInformation "| "
    echoVerbose "+====================================================="
    exit 143; # 128 + 15 -- SIGTERM
}

# Start the mariadb server as a deamon and execute it inside 
# the running shell
function startMariadbService {
    if [[ ! -f $DATA_PATH/.sxIsInit ]]; then
        init_service_mariadb
    fi
    trap 'stop_mariadb_handler' SIGHUP SIGINT SIGQUIT SIGTERM SIGKILL SIGSTOP SIGCONT
    exec mysqld_safe
    startDaemon
}