kind: ImageStreamList
apiVersion: v1
metadata:
  name: startx-os
  annotations:
    openshift.io/generated-by: STARTX
  labels:
    provider: startx
items:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: startx-os
      annotations:
        openshift.io/display-name: Startx Base OS (S2I)
        openshift.io/generated-by: STARTX
      labels:
        provider: startx
    spec:
      tags:
        - name: fc26
          annotations:
            openshift.io/display-name: S2I Startx Fedora 26
            description: Minimal Fedora 26 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: fc26
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/fedora:26
        - name: fc27
          annotations:
            openshift.io/display-name: S2I Startx Fedora 27
            description: Minimal Fedora 27 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: fc27
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/fedora:27
        - name: fc28
          annotations:
            openshift.io/display-name: S2I Startx Fedora 28
            description: Minimal Fedora 28 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: fc28
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/fedora:28
        - name: fc29
          annotations:
            openshift.io/display-name: S2I Startx Fedora 29
            description: Minimal Fedora 29 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: fc29
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/fedora:29
        - name: fc30
          annotations:
            openshift.io/display-name: S2I Startx Fedora 30
            description: Minimal Fedora 30 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: fc30
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/fedora:30
        - name: fc31
          annotations:
            openshift.io/display-name: S2I Startx Fedora 31
            description: Minimal Fedora 31 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: fc31
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/fedora:31
        - name: fc32
          annotations:
            openshift.io/display-name: S2I Startx Fedora 32
            description: Minimal Fedora 32 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: fc32
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/fedora:32
        - name: fc33
          annotations:
            openshift.io/display-name: S2I Startx Fedora 33
            description: Minimal Fedora 33 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: fc33
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/fedora:33
        - name: fc34
          annotations:
            openshift.io/display-name: S2I Startx Fedora 34
            description: Minimal Fedora 34 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: fc34
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/fedora:34
        - name: rawhide
          annotations:
            openshift.io/display-name: S2I Startx Fedora (rawhide)
            description: Minimal Fedora 27 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: rawhide
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/fedora:latest
        - name: ubi8
          annotations:
            openshift.io/display-name: S2I Startx RedHat UBI 8
            description: Minimal RedHat UBI 8 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,ubi
            supports: ubi
            version: "8"
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/ubi:8
        - name: centos8
          annotations:
            openshift.io/display-name: S2I Startx CentOS 8
            description: Minimal CentOS 8 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,centos
            supports: centos
            version: "8"
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/centos:8
        - name: centos7
          annotations:
            openshift.io/display-name: S2I Startx CentOS 7
            description: Minimal CentOS 7 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,centos
            supports: centos
            version: "7"
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/centos:7
        - name: centos6
          annotations:
            openshift.io/display-name: S2I Startx CentOS 6
            description: Minimal CentOS 6 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,centos
            supports: centos
            version: "6"
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/centos:6
        - name: alpine3
          annotations:
            openshift.io/display-name: S2I Startx Alpine 3
            description: Minimal Alpine 3 OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,alpine
            supports: alpine
            version: "3"
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: DockerImage
            name: startx/alpine:3
        - name: latest
          annotations:
            openshift.io/display-name: S2I Startx Fedora (latest)
            description: Minimal Fedora OS builder for bash operations
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: ImageStreamTag
            name: rawhide
        - name: dev
          annotations:
            openshift.io/display-name: S2I Startx Fedora (dev)
            description: Fedora OS builder for bash operations (developpement)
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: "dev"
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: ImageStreamTag
            name: rawhide
        - name: test
          annotations:
            openshift.io/display-name: S2I Startx Fedora (test)
            description: Fedora OS builder for bash operations (testing)
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: "test"
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: ImageStreamTag
            name: centos8
        - name: preprod
          annotations:
            openshift.io/display-name: S2I Startx Fedora (preprod)
            description: Fedora OS builder for bash operations (pre-production)
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: "pre-prod"
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: ImageStreamTag
            name: alpine3
        - name: prod
          annotations:
            openshift.io/display-name: S2I Startx Fedora (prod)
            description: Fedora OS builder for bash operations (production)
            iconClass: icon-beaker
            tags: builder,startx,fedora
            supports: fedora
            version: "prod"
            sampleRepo: https://github.com/startxfr/docker-images-example-bash.git
          from:
            kind: ImageStreamTag
            name: alpine3
