#!/bin/bash
source /var/lib/sx/sx
source /var/lib/sx/sx-php

# Display pma information
function pmaInformation {
    phpInformation $1 
}

# function executed when pre-deploy hook is called
function pmaPreDeploy {
    genericHeader
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME  running PRE-DEPLOY HOOK"
    echoNotVerbose "container $HOSTNAME  running PRE-DEPLOY HOOK"
    echoVerbose "| "
    pmaInformation "| "
    echoVerbose "+====================================================="
    echoVerbose "Create log directory $LOG_PATH"
    touch $LOG_PATH/access.log
    testAndRunSourceCodeScript "pre-deploy" 
}

# function executed when post-deploy hook is called
function pmaPostDeploy {
    genericHeader
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME  running POST-DEPLOY HOOK"
    echoNotVerbose "container $HOSTNAME  running POST-DEPLOY HOOK"
    echoVerbose "| "
    pmaInformation "| "
    echoVerbose "+====================================================="
    testAndRunSourceCodeScript "post-deploy" 
}

# function executed when pre-build hook is called
function pmaPostBuild {
    genericHeader
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME  running POST-BUILD HOOK"
    echoNotVerbose "container $HOSTNAME  running POST-BUILD HOOK"
    echoVerbose "| "
    pmaInformation "| "
    echoVerbose "+====================================================="
    testAndRunSourceCodeScript "post-build" 
}

# function executed when assemble hook is called
function pmaAssemble {
    genericHeader
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME  running ASSEMBLE"
    echoNotVerbose "container $HOSTNAME  running ASSEMBLE"
    echoVerbose "| "
    pmaInformation "| "
    echoVerbose "+====================================================="
    echo "Fixing perm on $S2I_DEST"
    if [[ -r $S2I_DEST ]]; then
      chown 1001:0 -R $S2I_DEST
      chmod g=u -R $S2I_DEST
      moveSourceCode $S2I_DEST $APP_PATH
    fi;
    testAndRunSourceCodeScript "assemble" 
}

# function executed on container startup
function pmaRun {
    genericHeader
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME is RUNNING"
    echoNotVerbose "container $HOSTNAME is RUNNING"
    echoVerbose "| "
    pmaInformation "| "
    echoVerbose "+====================================================="
    startPhpService
}

# Display liveness status
function pmaIsLive {
    genericIsLive
}

# Display readyness status
function pmaIsReady {
    apacheIsReady
}
