server:
  build: ./
  container_name: "service-postgres"
  mem_limit: 1g
  memswap_limit: 1g
  cpu_shares: 8
  restart: "on-failure:2"
  ports:
    - "9241:5432"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "postgresql"
    CONTAINER_INSTANCE: "service-postgres"
    POSTGRESQL_ROOT_PASSWORD: "secretdemerde"
    POSTGRESQL_USER: "user-test"
    POSTGRESQL_PASSWORD: "pwd-test"
    POSTGRESQL_DATABASE: "db_test"
  volumes:
    - "/tmp/container/logs/postgresql:/logs"
    - "/tmp/container/postgresql:/data"