postgres:
  build: ./
  container_name: "ubi8-service-postgres"
  mem_limit: 1g
  memswap_limit: 1g
  cpu_shares: 8
  restart: "on-failure:2"
  privileged: true
  ports:
    - "9241:5432"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "postgresql"
    POSTGRESQL_ROOT_PASSWORD: "secretdemerde"
    POSTGRESQL_USER: "user-test"
    POSTGRESQL_PASSWORD: "pwd-test"
    POSTGRESQL_DATABASE: "db_test"
#  volumes:
#    - "/tmp/container/postgres/logs:/logs:z"
#    - "/tmp/container/postgres/data:/data:z"
#  command:
#     - "/bin/sx-postgres"
#     - "run"