---
kind: Template
apiVersion: v1
metadata:
  name: startx-ooconv-template
  annotations:
    openshift.io/display-name: Startx LibreOffice converter (fedora)
    description: LibreOffice converter for document convertion running under Fedora
    iconClass: icon-aerogear
    tags: startx,os,fedora,ooconv,libreoffice
    openshift.io/long-description: This template provides an ooconv libreoffice webserver
      in a fedora container. Ready to use in openshift with a simple deployement config,
      or as a s2i builder for building web applications container. For more information
      about using this image, including OpenShift considerations, see https://github.com/startxfr/docker-images/blob/master/README.md.
    openshift.io/provider-display-name: STARTX
    openshift.io/documentation-url: https://github.com/startxfr/docker-images/blob/master/README.md
    openshift.io/support-url: https://github.com/startxfr/docker-images/issues/new
message: 'The following container have been created in your project: ${APP_NAME} and
  you can use openshift console to log into.'
labels:
  template: startx-ooconv-template
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    annotations:
      openshift.io/display-name: Startx LibreOffice converter
      openshift.io/generated-by: STARTX
    labels:
      app: "${APP_NAME}"
      type: "${APP_TYPE}"
      provider: startx
      template: startx-ooconv-template
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/display-name: Startx LibreOffice converter (Fedora rawhide)
        description: LibreOffice converter for document convertion running under Fedora
          rawhide
        iconClass: icon-aerogear
        tags: builder,startx,fedora,ooconv,libreoffice
        supports: http
        version: rawhide
        sampleRepo: https://github.com/startxfr/docker-images-example-ooconv.git
      from:
        kind: DockerImage
        name: startx/sv-ooconv:latest
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    generation: 2
    creationTimestamp: 
    labels:
      app: "${APP_NAME}"
      type: "${APP_TYPE}"
      provider: startx
      template: startx-ooconv-template
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 60
        maxUnavailable: 25%
        maxSurge: 25%
        pre:
          failurePolicy: Abort
          execNewPod:
            command:
            - "/bin/sx-ooconv"
            - pre-deploy
            containerName: "${APP_NAME}"
        post:
          failurePolicy: Abort
          execNewPod:
            command:
            - "/bin/sx-ooconv"
            - post-deploy
            containerName: "${APP_NAME}"
      resources: {}
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}"
        from:
          kind: ImageStreamTag
          name: "${APP_NAME}:latest"
    - type: ConfigChange
    postCommit:
      script: "/bin/sx-ooconv info"
    replicas: 1
    test: false
    selector:
      app: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    template:
      metadata:
        creationTimestamp: 
        labels:
          app: "${APP_NAME}"
          type: "${APP_TYPE}"
          provider: startx
          template: startx-ooconv-template
          deploymentconfig: "${APP_NAME}"
        annotations:
          openshift.io/generated-by: STARTX
      spec:
        containers:
        - name: "${APP_NAME}"
          image: " "
          command:
          - "/bin/sx-ooconv"
          args:
          - run
          resources: {}
          livenessProbe:
            exec:
              command:
              - "/bin/sx-ooconv"
              - isLive
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - "/bin/sx-ooconv"
              - isReady
            initialDelaySeconds: 2
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: Always
  status:
    observedGeneration: 2
    replicas: 1
    updatedReplicas: 1
    availableReplicas: 1
- kind: Route
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    creationTimestamp: 
    labels:
      app: "${APP_NAME}"
      type: "${APP_TYPE}"
      provider: startx
      template: startx-ooconv-template
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    to:
      kind: Service
      name: "${APP_NAME}"
      weight: 100
  status:
    ingress:
    - routerName: router
      conditions:
      - type: Admitted
        status: 'True'
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    creationTimestamp: 
    labels:
      app: "${APP_NAME}"
      type: "${APP_TYPE}"
      provider: startx
      template: startx-ooconv-template
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
parameters:
- name: APP_NAME
  displayName: Application name
  description: The name of the created application
  value: ooconv
  required: true
- name: APP_TYPE
  displayName: Application type
  description: The type of the created application
  value: system
