firefox:
  build: ./
  container_name: "vdi-firefox"
  ports:
    - "9267:5900"
  privileged: true
  environment:
    SX_FIREFOX_SCREEN_RES_X: "1600x900x24"
    SX_FIREFOX_SCREEN_RES_FIREFOX: "1600,900"
    SX_VERBOSE: 'true'
  volumes:
    - "/dev/shm:/dev/shm"
#    - "/mnt/firefox:/home/firefox:Z"
#  command:
#    - "/bin/sx-firefox"
#    - "run"
