kind: ImageStreamList
apiVersion: v1
metadata:
  name: startx-apache
  annotations:
    openshift.io/generated-by: STARTX
  labels:
    provider: startx
items:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: startx-apache
      annotations:
        openshift.io/display-name: Startx WebServer (S2I)
        openshift.io/generated-by: STARTX
      labels:
        provider: startx
    spec:
      tags:
        - name: fc26
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Fedora 26)
            description:
              Http server builder for simple web application running under
              Fedora 26
            iconClass: icon-apache
            tags: builder,startx,fedora,apache,httpd
            supports: http
            version: fc26
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:fc26
        - name: fc27
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Fedora 27)
            description:
              Http server builder for simple web application running under
              Fedora 27
            iconClass: icon-apache
            tags: builder,startx,fedora,apache,httpd
            supports: http
            version: fc27
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:fc27
        - name: fc28
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Fedora 28)
            description:
              Http server builder for simple web application running under
              Fedora 28
            iconClass: icon-apache
            tags: builder,startx,fedora,apache,httpd
            supports: http
            version: fc28
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:fc28
        - name: fc29
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Fedora 29)
            description:
              Http server builder for simple web application running under
              Fedora 29
            iconClass: icon-apache
            tags: builder,startx,fedora,apache,httpd
            supports: http
            version: fc29
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:fc29
        - name: fc30
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Fedora 30)
            description:
              Http server builder for simple web application running under
              Fedora 30
            iconClass: icon-apache
            tags: builder,startx,fedora,apache,httpd
            supports: http
            version: fc30
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:fc30
        - name: fc31
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Fedora 31)
            description:
              Http server builder for simple web application running under
              Fedora 31
            iconClass: icon-apache
            tags: builder,startx,fedora,apache,httpd
            supports: http
            version: fc31
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:fc31
        - name: fc32
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Fedora 32)
            description:
              Http server builder for simple web application running under
              Fedora 32
            iconClass: icon-apache
            tags: builder,startx,fedora,apache,httpd
            supports: http
            version: fc32
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:fc32
        - name: fc33
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Fedora 33)
            description:
              Http server builder for simple web application running under
              Fedora 33
            iconClass: icon-apache
            tags: builder,startx,fedora,apache,httpd
            supports: http
            version: fc33
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:fc33
        - name: fc34
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Fedora 34)
            description:
              Http server builder for simple web application running under
              Fedora 34
            iconClass: icon-apache
            tags: builder,startx,fedora,apache,httpd
            supports: http
            version: fc34
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:fc34
        - name: fc35
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Fedora 35)
            description:
              Http server builder for simple web application running under
              Fedora 35
            iconClass: icon-apache
            tags: builder,startx,fedora,apache,httpd
            supports: http
            version: fc35
            sampleRepo: https://github.com/startxfr/docker-images-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:fc35
        - name: rawhide
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Fedora rawhide)
            description:
              Http server builder for simple web application running under
              Fedora rawhide
            iconClass: icon-apache
            tags: builder,startx,fedora,apache,httpd
            supports: http
            version: rawhide
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:latest
        - name: ubi8
          annotations:
            openshift.io/display-name: S2I Startx WebServer (RedHat UBI 8)
            description:
              Http server builder for simple web application running under
              RedHat UBI 8
            iconClass: icon-apache
            tags: builder,startx,ubi,apache,httpd
            supports: http
            version: "8"
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:ubi8
        - name: alma8
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Alma 8)
            description:
              Http server builder for simple web application running under
              Alma 8
            iconClass: icon-apache
            tags: builder,startx,alma,apache,httpd
            supports: http
            version: "8"
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:alma8
        - name: rocky8
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Rocky 8)
            description:
              Http server builder for simple web application running under
              Rocky 8
            iconClass: icon-apache
            tags: builder,startx,rocky,apache,httpd
            supports: http
            version: "8"
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:rocky8
        - name: centos8
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Centos 8)
            description:
              Http server builder for simple web application running under
              Centos 8
            iconClass: icon-apache
            tags: builder,startx,centos,apache,httpd
            supports: http
            version: "8"
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:centos8
        - name: centos7
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Centos 7)
            description:
              Http server builder for simple web application running under
              Centos 7
            iconClass: icon-apache
            tags: builder,startx,centos,apache,httpd
            supports: http
            version: "7"
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:centos7
        - name: centos6
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Centos 6)
            description:
              Http server builder for simple web application running under
              Centos 6
            iconClass: icon-apache
            tags: builder,startx,centos,apache,httpd
            supports: http
            version: "6"
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:centos6
        - name: alpine3
          annotations:
            openshift.io/display-name: S2I Startx WebServer (Alpine 3)
            description:
              Http server builder for simple web application running under
              Alpine 3
            iconClass: icon-apache
            tags: builder,startx,alpine,apache,httpd
            supports: http
            version: "3"
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: DockerImage
            name: startx/sv-apache:alpine3
        - name: latest
          annotations:
            openshift.io/display-name: S2I Startx WebServer (latest)
            description:
              Http server builder for simple web application running under
              Fedora latest
            iconClass: icon-apache
            tags: builder,startx,alpine,apache,httpd
            supports: http
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: ImageStreamTag
            name: rawhide
        - name: dev
          annotations:
            openshift.io/display-name: S2I Startx WebServer (dev)
            description: Http server builder for simple web application (developpement)
            iconClass: icon-apache
            tags: builder,startx,alpine,apache,httpd
            supports: http
            version: "dev"
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: ImageStreamTag
            name: rawhide
        - name: test
          annotations:
            openshift.io/display-name: S2I Startx WebServer (test)
            description: Http server builder for simple web application (testing)
            iconClass: icon-apache
            tags: builder,startx,alpine,apache,httpd
            supports: http
            version: "test"
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: ImageStreamTag
            name: centos8
        - name: preprod
          annotations:
            openshift.io/display-name: S2I Startx WebServer (preprod)
            description: Http server builder for simple web application (pre-production)
            iconClass: icon-apache
            tags: builder,startx,alpine,apache,httpd
            supports: http
            version: "pre-prod"
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: ImageStreamTag
            name: alpine3
        - name: prod
          annotations:
            openshift.io/display-name: S2I Startx WebServer (prod)
            description: Http server builder for simple web application (production)
            iconClass: icon-apache
            tags: builder,startx,alpine,apache,httpd
            supports: http
            version: "prod"
            sampleRepo: https://gitlab.com/startx1/containers-example-apache.git
          from:
            kind: ImageStreamTag
            name: alpine3
