#!/bin/bash
source $SX_LIBDIR/sx

function check_apache_environment {
    if [ ! -v APP_PATH ]; then
        APP_PATH="/app"
        export APP_PATH
    fi
    if [ ! -v LOG_PATH ]; then
        LOG_PATH="/logs"
        export LOG_PATH
    fi
    if [ ! -n "$SERVER_NAME" ]; then
        SERVER_NAME="localhost"
        export SERVER_NAME
    fi
}

# Display apache information
function apacheInformation {
    displayInformation $1 
    echoVerbose $1 "app path  : $APP_PATH"
    echoVerbose $1 "log path  : $LOG_PATH"
    echoVerbose $1 "httpd     : $(httpd -v | head -1)" 
}

# function executed when pre-deploy hook is called
function apachePreDeploy {
    genericHeader
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME  running PRE-DEPLOY HOOK"
    echoNotVerbose "container $HOSTNAME  running PRE-DEPLOY HOOK"
    echoVerbose "| "
    apacheInformation "| "
    echoVerbose "+====================================================="
    testAndRunSourceCodeScript "pre-deploy"
    exit 0; 
}

# function executed when post-deploy hook is called
function apachePostDeploy {
    genericHeader
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME  running POST-DEPLOY HOOK"
    echoNotVerbose "container $HOSTNAME  running POST-DEPLOY HOOK"
    echoVerbose "| "
    apacheInformation "| "
    echoVerbose "+====================================================="
    testAndRunSourceCodeScript "post-deploy" 
    exit 0;
}

# function executed when pre-build hook is called
function apachePostBuild {
    genericHeader
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME  running POST-BUILD HOOK"
    echoNotVerbose "container $HOSTNAME  running POST-BUILD HOOK"
    echoVerbose "| "
    apacheInformation "| "
    echoVerbose "+====================================================="
    testAndRunSourceCodeScript "post-build" 
    exit 0;
}

# function executed when assemble hook is called
function apacheAssemble {
    genericHeader
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME  running ASSEMBLE"
    echoNotVerbose "container $HOSTNAME  running ASSEMBLE"
    echoVerbose "| "
    apacheInformation "| "
    echoVerbose "+====================================================="
    if [[ -d $S2I_DEST ]]; then
      echoVerbose "Fixing perm on $S2I_DEST"
      chown 1001:0 -R $S2I_DEST
      chmod g=u -R $S2I_DEST
      moveSourceCode $S2I_DEST $APP_PATH
    fi;
    testAndRunSourceCodeScript "assemble" 
    exit 0;
}

# function executed on container startup
function apacheRun {
    genericHeader
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME is RUNNING"
    echoNotVerbose "container $HOSTNAME is RUNNING"
    echoVerbose "| "
    apacheInformation "| "
    echoVerbose "+====================================================="
    startApacheService
}

# Display liveness status
function apacheIsLive {
    R=`curl -sL -w "%{http_code}\\n" "http://localhost/" -o /dev/null`
    if [ "$R" = "200" ]; then
      exit 0;
    else 
      exit 1;
    fi;
}

# Display readyness status
function apacheIsReady {
    genericIsReady
}

# function executed on apahce service stop
function stopApacheHandler {
    killall httpd
    rm -rf /run/httpd/*
    echoVerbose "+====================================================="
    echoVerbose "| Container $HOSTNAME is now STOPPED"
    echoNotVerbose "container is now stopped"
    echoVerbose "| "
    apacheInformation "| "
    echoVerbose "+====================================================="
    exit 143; # 128 + 15 -- SIGTERM
}

# Start the httpd server as a deamon and execute it inside 
# the running shell
function startApacheService {
    trap 'kill ${!}; stopApacheHandler' SIGHUP SIGINT SIGQUIT SIGTERM SIGKILL SIGSTOP SIGCONT
    rm -rf /run/httpd/* /tmp/httpd*
    touch $LOG_PATH/access.log
    touch /var/log/httpd/access.log
    exec /usr/sbin/httpd -D FOREGROUND > $LOG_PATH/access.log &
    while true
    do
        tail -f $LOG_PATH/*.log & tail -f /var/log/httpd/*.log & wait ${!}
    done
}

# set env var $2 (val $3) in file $1
function setEnvironmentVariableInFile {
    if [ -z "$3" ]; then
            echoVerbose "Environment variable '$2' not set."
            return
    fi
    echo "SetEnv $2 $3" >> $1
}

function setSys2HttpEnvironmentVariable {
    echoVerbose "adding environement to $1"
    echo "" >> $1
    for _curVar in `env | awk -F = '{print $1}'`;do
        setEnvironmentVariableInFile $1 ${_curVar} ${!_curVar}
    done
}