#!/bin/bash

function check_couchbase_environment {
    if [ ! -v DATA_PATH ]; then
        DATA_PATH="/data"
        export DATA_PATH
    fi
    if [ ! -v LOG_PATH ]; then
        LOG_PATH="/logs"
        export LOG_PATH
    fi
}

function couchbaseInformation {
    displayInformation $1
    echoVerbose $1 "version   : $SX_VERSION"
    echoVerbose $1 "engine    : v$CB_VERSION"
    echoVerbose $1 "log path  : $LOG_PATH"
    echoVerbose $1 "data path : $DATA_PATH"
}

function displayCouchbaseRunInformation {
    couchbaseInformation $1
    echoVerbose $1 "admin     : $COUCHBASE_USER:$COUCHBASE_PASSWORD"
    echo $1 "database  : $COUCHBASE_BUCKETS"
}

function couchbasePreDeploy {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running PRE-DEPLOY HOOK"
    echoVerbose "| "
    couchbaseInformation "| "
    echo "+====================================================="
}

function couchbasePostDeploy {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running POST-DEPLOY HOOK"
    echoVerbose "| "
    couchbaseInformation "| "
    echo "+====================================================="
}

function couchbasePostBuild {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running POST-BUILD HOOK"
    echoVerbose "| "
    couchbaseInformation "| "
    echo "+====================================================="
}

function couchbaseAssemble {
    echo "+====================================================="
    echo "| Container $HOSTNAME is running ASSEMBLE"
    echoVerbose "| "
    couchbaseInformation "| "
    echo "+====================================================="
    echo "Fixing perm on /tmp/src"
    chown 1001:0 -R /tmp/src
    chmod g=u -R /tmp/src
}

function couchbaseRun {
    echo "+====================================================="
    echo "| Container $HOSTNAME is RUNNING"
    echoVerbose "| "
    couchbaseInformation "| "
    echo "+====================================================="
    startCouchbaseService
}

function stop_couchbase_handler {
    couchbaseadmin -uroot shutdown
    echo "+====================================================="
    echo "| Container $HOSTNAME is now STOPPED"
    echoVerbose "| "
    couchbaseInformation "| "
    echo "+====================================================="
    exit 143; # 128 + 15 -- SIGTERM
}

# Start the couchbase server as a deamon and execute it inside 
# the running shell
function startCouchbaseService {
    exec 2>&1
    cd /opt/couchbase
    mkdir -p var/lib/couchbase \
             var/lib/couchbase/config \
             var/lib/couchbase/data \
             var/lib/couchbase/stats \
             var/lib/couchbase/logs \
             var/lib/moxi
    chown -R couchbase:couchbase var
    chgrp -R 0 var
    chmod -R g=u var
    trap 'kill ${!}; stop_couchbase_handler' SIGHUP SIGINT SIGQUIT SIGTERM SIGKILL SIGSTOP SIGCONT
    exec /opt/couchbase/bin/couchbase-server -- -kernel global_enable_tracing false -noinput
}