#!/bin/bash
echo "========> END BUILD ENVIRONMENT"
if [ "$1" = true ] ; then
    echo "========> Build was fully performed with success"
    echo 0
else
    echo "--------> Build was partially performed"
    echo 2;
fi