#!/bin/bash
echo "========> END BUILD ENVIRONMENT"
if [ "$1" = true ] ; then
    echo "========> Build was fully performed with success"
    echo 0
else
    echo "--------> Build was partially performed"
    echo "!!!!!!!!> An error happened in your build"
    if [ "$SX_DEBUG" = true ] ; then
        echo $TRAVIS_TEST_RESULT
    fi
    if [[ "$ISFATAL" = "true" ]]; then
        exit 2;
    else
        exit 0;
    fi
fi