#!/bin/bash
export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH:1} ; fi`

function dockerPublish {
    cd $1/
    docker build -f Dockerfile --squash -t $2:$TAG .
    docker push $2
    cd -
}

echo "========> BUILD & PUBLISH $2:$TAG Container (public)"
dockerPublish $1 $2
exit 0;