#!/bin/bash

echo "========> PUBLISH Container image $NAMESPACE/$2:$3"
if [ -f /tmp/istested_$2 ] ; then
    rm -f /tmp/istested_$2
    RESULT=$(docker push $NAMESPACE/$2)
    if [ "$SX_DEBUG" = true ] ; then
        echo $RESULT
    fi
    if [[ $? = "0" ]]; then
        echo "========> PUBLISHED Container image $NAMESPACE/$2:$3"
        exit 0;
    else
        echo "!! Could not publish container image $NAMESPACE/$2:$3"
        if [[ "$ISFATAL" = "true" ]]; then
            exit 1;
        else
            exit 0;
        fi
    fi
else
    echo "========> PUBLISHING Container image $NAMESPACE/$2:$3 skipped because test failed"
    exit 0;
fi