#!/bin/bash


function dockerBuild {
    sudo docker-compose -f docker-compose-$1.yml build $2
}

function dockerRun {
    sudo docker-compose -f docker-compose-$1.yml up -d $2
}

echo "========> BUILD & START $1 $2"
dockerBuild $1 $2
dockerRun $1 $2
exit 0;