---
kind: Template
apiVersion: v1
metadata:
  name: startx-sv-php-deploy-template
  annotations:
    openshift.io/display-name: Startx PHP Server (ephemeral deploy workflow)
    description: Deployement workflow of a dynamic PHP web application using ephemeral storage
      for logs records. Use apache with various underlying linux distribution. See 
      https://hub.docker.com/r/startx/sv-php
    iconClass: icon-php
    tags: startx,os,fedora,php,httpd
    openshift.io/provider-display-name: STARTX
    openshift.io/documentation-url: https://hub.docker.com/r/startx/sv-php
    openshift.io/support-url: https://github.com/startxfr/docker-images/issues/new
message: |-
  Your dynamic web application ${APP_NAME} is deploying...

  Service name: ${APP_NAME}
  action      : ${RUN_ACTION}
labels:
  template: startx-sv-php-deploy-template
  provider: startx 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    annotations:
      openshift.io/display-name: Startx PHP WebServer for application ${APP_NAME}
      openshift.io/generated-by: STARTX
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
  spec:
    tags:
    - name: fc26
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Fedora 26)
        description: PHP+Http server builder for dynamic web application running under
          Fedora 26
        iconClass: icon-php
        tags: builder,startx,fedora,php,httpd
        supports: http
        version: fc26
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:fc26
    - name: fc27
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Fedora 27)
        description: PHP+Http server builder for dynamic web application running under
          Fedora 27
        iconClass: icon-php
        tags: builder,startx,fedora,php,httpd
        supports: http
        version: fc27
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:fc27
    - name: fc28
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Fedora 28)
        description: PHP+Http server builder for dynamic web application running under
          Fedora 28
        iconClass: icon-php
        tags: builder,startx,fedora,php,httpd
        supports: http
        version: fc28
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:fc28
    - name: fc29
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Fedora 29)
        description: PHP+Http server builder for dynamic web application running under
          Fedora 29
        iconClass: icon-php
        tags: builder,startx,fedora,php,httpd
        supports: http
        version: fc29
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:fc29
    - name: fc30
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Fedora 30)
        description: PHP+Http server builder for dynamic web application running under
          Fedora 30
        iconClass: icon-php
        tags: builder,startx,fedora,php,httpd
        supports: http
        version: fc30
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:fc30
    - name: rawhide
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Fedora rawhide)
        description: PHP+Http server builder for dynamic web application running under
          Fedora rawhide
        iconClass: icon-php
        tags: builder,startx,fedora,php,httpd
        supports: http
        version: rawhide
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:latest
    - name: centos7
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Centos 7)
        description: PHP+Http server builder for dynamic web application running under
          Centos 7
        iconClass: icon-php
        tags: builder,startx,centos,php,httpd
        supports: http
        version: '7'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:centos7
    - name: centos6
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Centos 6)
        description: PHP+Http server builder for dynamic web application running under
          Centos 6
        iconClass: icon-php
        tags: builder,startx,centos,php,httpd
        supports: http
        version: '7'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:centos6
    - name: alpine3
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Alpine 3)
        description: PHP+Http server builder for dynamic web application running under
          Alpine 3
        iconClass: icon-php
        tags: builder,startx,alpine,php,httpd
        supports: http
        version: '3'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:alpine3
    - name: latest
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (latest)
        description: PHP+Http server builder for dynamic web application running under
          Fedora latest
        iconClass: icon-php
        tags: builder,startx,alpine,php,httpd
        supports: http
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: ImageStreamTag
        name: rawhide
    - name: dev
      annotations:
        openshift.io/display-name: S2I Startx PHP WebServer (dev)
        description: Http server builder for dynamic web application (developpement)
        iconClass: icon-php
        tags: builder,startx,alpine,php,httpd
        supports: http
        version: 'dev'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: ImageStreamTag
        name: rawhide
    - name: test
      annotations:
        openshift.io/display-name: S2I Startx PHP WebServer (test)
        description: Http server builder for dynamic web application (testing)
        iconClass: icon-php
        tags: builder,startx,alpine,php,httpd
        supports: http
        version: 'test'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: ImageStreamTag
        name: centos7
    - name: preprod
      annotations:
        openshift.io/display-name: S2I Startx PHP WebServer (preprod)
        description: Http server builder for dynamic web application (pre-production)
        iconClass: icon-php
        tags: builder,startx,alpine,php,httpd
        supports: http
        version: 'pre-prod'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: ImageStreamTag
        name: alpine3
    - name: prod
      annotations:
        openshift.io/display-name: S2I Startx PHP WebServer (prod)
        description: Http server builder for dynamic web application (production)
        iconClass: icon-php
        tags: builder,startx,alpine,php,httpd
        supports: http
        version: 'prod'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: ImageStreamTag
        name: alpine3
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: "${APP_NAME}-config"
    annotations:
      openshift.io/display-name: Application ${APP_NAME} configuration
      openshift.io/generated-by: STARTX
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
  data:
    SX_ID: ${APP_NAME}/${APP_STAGE}
    SX_TYPE: ${APP_STAGE}
    SX_SERVICE: ${APP_NAME}
    SX_NAME: Static web application ${APP_NAME}
    SX_SUMMARY: Static web application ${APP_NAME} based on fedora container
    SX_VERSION: 0.0.1 
    APP_PATH: "${APP_PATH}"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 40
        pre:
          failurePolicy: Abort
          execNewPod:
            command:
            - "/bin/sx-php"
            - pre-deploy
            env:
            - name: SX_VERBOSE
              value: 'true'
            - name: SX_DEBUG
              value: 'true'
            envFrom:
              - configMapRef:
                  name: ${APP_NAME}-config
            containerName: "${APP_NAME}"
        post:
          failurePolicy: Abort
          execNewPod:
            command:
            - "/bin/sx-php"
            - post-deploy
            env:
            - name: SX_VERBOSE
              value: 'true'
            - name: SX_DEBUG
              value: 'true'
            envFrom:
              - configMapRef:
                  name: ${APP_NAME}-config
            containerName: "${APP_NAME}"
      resources: {}
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}"
        from:
          kind: ImageStreamTag
          name: "${APP_NAME}:${IMAGE_STAGE}"
    - type: ConfigChange
    postCommit:
      script: "/bin/sx-php info"
    replicas: 1
    test: false
    selector:
      app: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    template:
      metadata:
        creationTimestamp: 
        labels:
          app: "${APP_NAME}"
          provider: startx
          template: startx-sv-php-deploy-template
          deploymentconfig: "${APP_NAME}"
        annotations:
          openshift.io/generated-by: STARTX
      spec:
        containers:
        - name: "${APP_NAME}"
          image: " "
          env:
          - name: SX_VERBOSE
            value: 'true'
          envFrom:
            - configMapRef:
                name: ${APP_NAME}-config
          command:
          - "/bin/sx-php"
          args:
          - "${RUN_ACTION}"
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          livenessProbe:
            exec:
              command:
              - "/bin/sx-php"
              - isLive
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - "/bin/sx-php"
              - isReady
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: Always
          volumeMounts:
          - name: "${APP_NAME}-log"
            mountPath: "/var/log/httpd"
        volumes:
        - name: "${APP_NAME}-log"
          emptyDir:
            medium: ''
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        securityContext: {}
        dnsPolicy: ClusterFirst
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    to:
      kind: Service
      name: "${APP_NAME}"
      weight: 100
parameters:
- name: APP_NAME
  displayName: Application name
  description: The name of the created application
  value: php
  required: true
- name: APP_STAGE
  displayName: Application stage
  description: "Stage of the application deployed (ex: dev, test, prod, example, demo, poc, ...)"
  value: example
  required: true
- name: IMAGE_STAGE
  displayName: Image stage
  description: "Stage of the base image used (ex: dev, test, preprod, prod, latest, rawhide, fc30, alpine3, centos6, centos7, fc29, fc28, ...)"
  value: latest
  required: true
- name: RUN_ACTION
  displayName: Main action to perfom
  description: Action to perform for this running Pod. Should be one of build, post-build,
    pre-deploy, post-deploy, run, isLive, isReady, usage, usageS2i, daemon, info,
    version. See documentation for action list.
  value: run
  required: true
- name: APP_PATH
  displayName: Path to the application
  description: Container path to the application. Could be a mounted directory with
    your web content. Default is /app as defined in the startx/sv-php content.
  value: "/app"
  required: true
