kind: Template
apiVersion: v1
metadata:
  name: startx-sv-php-build-template
  annotations:
    openshift.io/display-name: Startx PHP WebServer (fedora)
    description: PHP+Http server for dynamic web application running under Fedora
    iconClass: icon-php
    tags: startx,os,fedora,php,httpd
    openshift.io/long-description: This template provides an php httpd webserver
      in a fedora container. Ready to use in openshift with a simple deployement config,
      or as a s2i builder for building web applications container. For more information
      about using this image, including OpenShift considerations, see https://github.com/startxfr/docker-images/blob/master/README.md.
    openshift.io/provider-display-name: STARTX
    openshift.io/documentation-url: https://github.com/startxfr/docker-images/blob/master/README.md
    openshift.io/support-url: https://github.com/startxfr/docker-images/issues/new
message: |-
  Your dynamic web application ${APP_NAME} is building and will be soon deployed...

  Service name: ${APP_NAME}
  Source      : ${SOURCE_GIT}
  action      : ${RUN_ACTION}
labels:
  template: startx-sv-php-build-template
  provider: startx 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: startx-sv-php
    annotations:
      openshift.io/display-name: Startx PHP WebServer
      openshift.io/generated-by: STARTX
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
  spec:
    tags:
    - name: fc26
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Fedora 26)
        description: PHP+Http server builder for dynamic web application running under
          Fedora 26
        iconClass: icon-php
        tags: builder,startx,fedora,php,httpd
        supports: http
        version: fc26
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:fc26
    - name: fc27
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Fedora 27)
        description: PHP+Http server builder for dynamic web application running under
          Fedora 27
        iconClass: icon-php
        tags: builder,startx,fedora,php,httpd
        supports: http
        version: fc27
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:fc27
    - name: fc28
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Fedora 28)
        description: PHP+Http server builder for dynamic web application running under
          Fedora 28
        iconClass: icon-php
        tags: builder,startx,fedora,php,httpd
        supports: http
        version: fc28
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:fc28
    - name: fc29
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Fedora 29)
        description: PHP+Http server builder for dynamic web application running under
          Fedora 29
        iconClass: icon-php
        tags: builder,startx,fedora,php,httpd
        supports: http
        version: fc29
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:fc29
    - name: fc30
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Fedora 30)
        description: PHP+Http server builder for dynamic web application running under
          Fedora 30
        iconClass: icon-php
        tags: builder,startx,fedora,php,httpd
        supports: http
        version: fc30
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:fc30
    - name: rawhide
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Fedora rawhide)
        description: PHP+Http server builder for dynamic web application running under
          Fedora rawhide
        iconClass: icon-php
        tags: builder,startx,fedora,php,httpd
        supports: http
        version: rawhide
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:latest
    - name: centos7
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Centos 7)
        description: PHP+Http server builder for dynamic web application running under
          Centos 7
        iconClass: icon-php
        tags: builder,startx,centos,php,httpd
        supports: http
        version: '7'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:centos7
    - name: centos6
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Centos 6)
        description: PHP+Http server builder for dynamic web application running under
          Centos 6
        iconClass: icon-php
        tags: builder,startx,centos,php,httpd
        supports: http
        version: '7'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:centos6
    - name: alpine3
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (Alpine 3)
        description: PHP+Http server builder for dynamic web application running under
          Alpine 3
        iconClass: icon-php
        tags: builder,startx,alpine,php,httpd
        supports: http
        version: '3'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: DockerImage
        name: startx/sv-php:alpine3
    - name: latest
      annotations:
        openshift.io/display-name: S2I Startx PHP PHP WebServer (latest)
        description: PHP+Http server builder for dynamic web application running under
          Fedora latest
        iconClass: icon-php
        tags: builder,startx,alpine,php,httpd
        supports: http
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: ImageStreamTag
        name: rawhide
    - name: dev
      annotations:
        openshift.io/display-name: S2I Startx PHP WebServer (dev)
        description: Http server builder for dynamic web application (developpement)
        iconClass: icon-php
        tags: builder,startx,alpine,php,httpd
        supports: http
        version: 'dev'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: ImageStreamTag
        name: rawhide
    - name: test
      annotations:
        openshift.io/display-name: S2I Startx PHP WebServer (test)
        description: Http server builder for dynamic web application (testing)
        iconClass: icon-php
        tags: builder,startx,alpine,php,httpd
        supports: http
        version: 'test'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: ImageStreamTag
        name: centos7
    - name: preprod
      annotations:
        openshift.io/display-name: S2I Startx PHP WebServer (preprod)
        description: Http server builder for dynamic web application (pre-production)
        iconClass: icon-php
        tags: builder,startx,alpine,php,httpd
        supports: http
        version: 'pre-prod'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: ImageStreamTag
        name: alpine3
    - name: prod
      annotations:
        openshift.io/display-name: S2I Startx PHP WebServer (prod)
        description: Http server builder for dynamic web application (production)
        iconClass: icon-php
        tags: builder,startx,alpine,php,httpd
        supports: http
        version: 'prod'
        sampleRepo: https://github.com/startxfr/docker-images-example-php.git
      from:
        kind: ImageStreamTag
        name: alpine3
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    annotations:
      openshift.io/display-name: Application ${APP_NAME}
      openshift.io/generated-by: STARTX
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/display-name: Application ${APP_NAME}
        description: Base image for the application ${APP_NAME}
        iconClass: icon-php
        tags: startx,fedora,php,httpd,application,${APP_NAME}
        supports: http
        version: latest
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: "${APP_NAME}-config"
    annotations:
      openshift.io/display-name: Application ${APP_NAME} configuration
      openshift.io/generated-by: STARTX
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
  data:
    SX_ID: ${APP_NAME}/${APP_STAGE}
    SX_TYPE: ${APP_STAGE}
    SX_SERVICE: ${APP_NAME}
    SX_NAME: Static web application ${APP_NAME}
    SX_SUMMARY: Static web application ${APP_NAME} based on fedora container
    SX_VERSION: 0.0.1 
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    triggers:
    - type: GitHub
      github:
        secret: "${WEBHOOK_TOKEN}_${APP_NAME}"
    - type: Generic
      generic:
        secret: "${WEBHOOK_TOKEN}_${APP_NAME}"
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
    runPolicy: SerialLatestOnly
    source:
      type: Git
      git:
        uri: "${SOURCE_GIT}"
        ref: "${SOURCE_BRANCH}"
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: startx-sv-php:${IMAGE_STAGE}
        env:
        - name: SX_VERBOSE
          value: 'true'
    output:
      to:
        kind: ImageStreamTag
        name: "${APP_NAME}:latest"
    resources: {}
    postCommit:
      command:
      - "/bin/sx-php"
      - post-build
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 20
        maxUnavailable: 25%
        maxSurge: 25%
        pre:
          failurePolicy: Abort
          execNewPod:
            containerName: "${APP_NAME}"
            command:
            - "/bin/sx-php"
            - pre-deploy
            env:
            - name: SX_VERBOSE
              value: 'true'
            - name: SX_DEBUG
              value: 'true'
            envFrom:
              - configMapRef:
                  name: ${APP_NAME}-config
        post:
          failurePolicy: Abort
          execNewPod:
            containerName: "${APP_NAME}"
            command:
            - "/bin/sx-php"
            - post-deploy
            env:
            - name: SX_VERBOSE
              value: 'true'
            - name: SX_DEBUG
              value: 'true'
            envFrom:
              - configMapRef:
                  name: ${APP_NAME}-config
      resources: {}
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}"
        from:
          kind: ImageStreamTag
          name: "${APP_NAME}:latest"
    - type: ConfigChange
    postCommit:
      script: "/bin/sx-php info"
    replicas: 1
    test: false
    selector:
      app: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    template:
      metadata:
        labels:
          app: "${APP_NAME}"
          deploymentconfig: "${APP_NAME}"
        annotations:
          openshift.io/generated-by: STARTX
      spec:
        containers:
        - name: "${APP_NAME}"
          image: " "
          env:
          - name: SX_VERBOSE
            value: 'true'
          envFrom:
            - configMapRef:
                name: ${APP_NAME}-config
          command:
          - "/bin/sx-php"
          args:
          - run
          resources: {}
          ports:
          - containerPort: 8080
            protocol: TCP
          livenessProbe:
            exec:
              command:
              - "/bin/sx-php"
              - isLive
            initialDelaySeconds: 4
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - "/bin/sx-php"
              - isReady
            initialDelaySeconds: 4
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: Always
          volumeMounts:
          - name: "${APP_NAME}-log"
            mountPath: "/var/log/httpd"
          - name: "${APP_NAME}-app"
            mountPath: "/app"
        volumes:
        - name: "${APP_NAME}-log"
          emptyDir:
            medium: ''
        - name: "${APP_NAME}-app"
          emptyDir:
            medium: ''
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        securityContext: {}
        dnsPolicy: ClusterFirst
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      stage: "${APP_STAGE}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    to:
      kind: Service
      name: "${APP_NAME}"
      weight: 100
parameters:
- name: APP_NAME
  displayName: Application name
  description: The name of the created application
  value: php
  required: true
- name: APP_STAGE
  displayName: Application stage
  description: "Stage of the application deployed (ex: dev, test, prod, example, demo, poc, ...)"
  value: example
  required: true
- name: IMAGE_STAGE
  displayName: Image stage
  description: "Stage of the base image used (ex: dev, test, preprod, prod, latest, rawhide, fc30, alpine3, centos6, centos7, fc29, fc28, ...)"
  value: latest
  required: true
- name: SOURCE_GIT
  displayName: Source repository
  description: URL to the source code to use during build process
  value: https://github.com/startxfr/docker-images-example-php.git
  required: true
- name: SOURCE_BRANCH
  displayName: Source branch
  description: Name of the default branch
  value: master
  required: true
- name: WEBHOOK_TOKEN
  displayName: Webhook token
  description: Secret token to use for webhook to github or generic
  generate: expression
  from: "[a-zA-Z0-9]{24}"
  required: true
- name: RUN_ACTION
  displayName: Main action to perfom
  description: Action to perform for this running Pod. Should be one of build, post-build,
    pre-deploy, post-deploy, run, isLive, isReady, usage, usageS2i, daemon, info,
    version. See documentation for action list.
  value: run
  required: true
