kind: ImageStreamList
apiVersion: v1
metadata:
  name: startx-mariadb
  annotations:
    openshift.io/generated-by: STARTX
  labels:
    provider: startx
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: startx-mariadb
    annotations:
      openshift.io/display-name: Startx Mariadb Database (S2I)
      openshift.io/generated-by: STARTX
    labels:
      provider: startx
  spec:
    tags:
    - name: fc26
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (Fedora 26)
        description: MariaDB server builder for simple SQL database running under
          Fedora 26
        iconClass: icon-mariadb
        tags: builder,startx,fedora,mariadb,sql
        supports: mysql
        version: fc26
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: DockerImage
        name: startx/sv-mariadb:fc26
    - name: fc27
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (Fedora 27)
        description: MariaDB server builder for simple SQL database running under
          Fedora 27
        iconClass: icon-mariadb
        tags: builder,startx,fedora,mariadb,sql
        supports: mysql
        version: fc27
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: DockerImage
        name: startx/sv-mariadb:fc27
    - name: fc28
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (Fedora 28)
        description: MariaDB server builder for simple SQL database running under
          Fedora 28
        iconClass: icon-mariadb
        tags: builder,startx,fedora,mariadb,sql
        supports: mysql
        version: fc28
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: DockerImage
        name: startx/sv-mariadb:fc28
    - name: fc29
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (Fedora 29)
        description: MariaDB server builder for simple SQL database running under
          Fedora 29
        iconClass: icon-mariadb
        tags: builder,startx,fedora,mariadb,sql
        supports: mysql
        version: fc29
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: DockerImage
        name: startx/sv-mariadb:fc29
    - name: fc31
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (Fedora 31)
        description: MariaDB server builder for simple SQL database running under
          Fedora 31
        iconClass: icon-mariadb
        tags: builder,startx,fedora,mariadb,sql
        supports: mysql
        version: fc31
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: DockerImage
        name: startx/sv-mariadb:fc31
    - name: rawhide
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (Fedora rawhide)
        description: MariaDB server builder for simple SQL database running under
          Fedora rawhide
        iconClass: icon-mariadb
        tags: builder,startx,fedora,mariadb,sql
        supports: mysql
        version: rawhide
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: DockerImage
        name: startx/sv-mariadb:latest
    - name: centos7
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (Centos 7)
        description: MariaDB server builder for simple SQL database running under
          Centos 7
        iconClass: icon-mariadb
        tags: builder,startx,centos,mariadb,sql
        supports: mysql
        version: '7'
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: DockerImage
        name: startx/sv-mariadb:centos7
    - name: centos6
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (Centos 6)
        description: MariaDB server builder for simple SQL database running under
          Centos 6
        iconClass: icon-mariadb
        tags: builder,startx,centos,mariadb,sql
        supports: mysql
        version: '7'
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: DockerImage
        name: startx/sv-mariadb:centos6
    - name: alpine3
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (Alpine 3)
        description: MariaDB server builder for simple SQL database running under
          Alpine 3
        iconClass: icon-mariadb
        tags: builder,startx,alpine,mariadb,sql
        supports: mysql
        version: '3'
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: DockerImage
        name: startx/sv-mariadb:alpine3
    - name: latest
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (latest)
        description: MariaDB server builder for simple SQL database running under
          Fedora latest
        iconClass: icon-mariadb
        tags: builder,startx,alpine,mariadb,sql
        supports: mysql
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: ImageStreamTag
        name: rawhide
    - name: dev
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (dev)
        description: MariaDB server builder for simple SQL database (developpement)
        iconClass: icon-mariadb
        tags: builder,startx,alpine,mariadb,sql
        supports: mysql
        version: 'dev'
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: ImageStreamTag
        name: rawhide
    - name: test
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (test)
        description: MariaDB server builder for simple SQL database (testing)
        iconClass: icon-mariadb
        tags: builder,startx,alpine,mariadb,sql
        supports: mysql
        version: 'test'
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: ImageStreamTag
        name: centos7
    - name: preprod
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (preprod)
        description: MariaDB server builder for simple SQL database (pre-production)
        iconClass: icon-mariadb
        tags: builder,startx,alpine,mariadb,sql
        supports: mysql
        version: 'pre-prod'
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: ImageStreamTag
        name: alpine3
    - name: prod
      annotations:
        openshift.io/display-name: S2I Startx Mariadb Database (prod)
        description: MariaDB server builder for simple SQL database (production)
        iconClass: icon-mariadb
        tags: builder,startx,alpine,mariadb,sql
        supports: mysql
        version: 'prod'
        sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
      from:
        kind: ImageStreamTag
        name: alpine3
