kind: ImageStreamList
apiVersion: v1
metadata:
  name: startx-mariadb
  annotations:
    openshift.io/generated-by: STARTX
  labels:
    provider: startx
items:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: startx-mariadb
      annotations:
        openshift.io/display-name: Startx Mariadb Database (S2I)
        openshift.io/generated-by: STARTX
      labels:
        provider: startx
    spec:
      tags:
        - name: fc26
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Fedora 26)
            description:
              MariaDB server builder for simple SQL database running under
              Fedora 26
            iconClass: icon-mariadb
            tags: builder,startx,fedora,mariadb,sql
            supports: mysql
            version: fc26
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:fc26
        - name: fc27
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Fedora 27)
            description:
              MariaDB server builder for simple SQL database running under
              Fedora 27
            iconClass: icon-mariadb
            tags: builder,startx,fedora,mariadb,sql
            supports: mysql
            version: fc27
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:fc27
        - name: fc28
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Fedora 28)
            description:
              MariaDB server builder for simple SQL database running under
              Fedora 28
            iconClass: icon-mariadb
            tags: builder,startx,fedora,mariadb,sql
            supports: mysql
            version: fc28
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:fc28
        - name: fc29
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Fedora 29)
            description:
              MariaDB server builder for simple SQL database running under
              Fedora 29
            iconClass: icon-mariadb
            tags: builder,startx,fedora,mariadb,sql
            supports: mysql
            version: fc29
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:fc29
        - name: fc30
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Fedora 30)
            description:
              MariaDB server builder for simple SQL database running under
              Fedora 30
            iconClass: icon-mariadb
            tags: builder,startx,fedora,mariadb,sql
            supports: mysql
            version: fc30
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:fc30
        - name: fc31
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Fedora 31)
            description:
              MariaDB server builder for simple SQL database running under
              Fedora 31
            iconClass: icon-mariadb
            tags: builder,startx,fedora,mariadb,sql
            supports: mysql
            version: fc31
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:fc31
        - name: fc32
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Fedora 32)
            description:
              MariaDB server builder for simple SQL database running under
              Fedora 32
            iconClass: icon-mariadb
            tags: builder,startx,fedora,mariadb,sql
            supports: mysql
            version: fc32
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:fc32
        - name: fc33
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Fedora 33)
            description:
              MariaDB server builder for simple SQL database running under
              Fedora 33
            iconClass: icon-mariadb
            tags: builder,startx,fedora,mariadb,sql
            supports: mysql
            version: fc33
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:fc33
        - name: fc34
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Fedora 34)
            description:
              MariaDB server builder for simple SQL database running under
              Fedora 34
            iconClass: icon-mariadb
            tags: builder,startx,fedora,mariadb,sql
            supports: mysql
            version: fc34
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:fc34
        - name: fc35
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Fedora 35)
            description:
              MariaDB server builder for simple SQL database running under
              Fedora 35
            iconClass: icon-mariadb
            tags: builder,startx,fedora,mariadb,sql
            supports: mysql
            version: fc35
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:fc35
        - name: rawhide
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Fedora rawhide)
            description:
              MariaDB server builder for simple SQL database running under
              Fedora rawhide
            iconClass: icon-mariadb
            tags: builder,startx,fedora,mariadb,sql
            supports: mysql
            version: rawhide
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:latest
        - name: ubi8
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (RedHat UBI 8)
            description:
              MariaDB server builder for simple SQL database running under
              RedHat UBI 8
            iconClass: icon-mariadb
            tags: builder,startx,ubi,mariadb,sql
            supports: mysql
            version: "8"
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:ubi8
        - name: centos8
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Centos 8)
            description:
              MariaDB server builder for simple SQL database running under
              Centos 8
            iconClass: icon-mariadb
            tags: builder,startx,centos,mariadb,sql
            supports: mysql
            version: "8"
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:centos8
        - name: centos7
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Centos 7)
            description:
              MariaDB server builder for simple SQL database running under
              Centos 7
            iconClass: icon-mariadb
            tags: builder,startx,centos,mariadb,sql
            supports: mysql
            version: "7"
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:centos7
        - name: centos6
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Centos 6)
            description:
              MariaDB server builder for simple SQL database running under
              Centos 6
            iconClass: icon-mariadb
            tags: builder,startx,centos,mariadb,sql
            supports: mysql
            version: "6"
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:centos6
        - name: alpine3
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (Alpine 3)
            description:
              MariaDB server builder for simple SQL database running under
              Alpine 3
            iconClass: icon-mariadb
            tags: builder,startx,alpine,mariadb,sql
            supports: mysql
            version: "3"
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: DockerImage
            name: startx/sv-mariadb:alpine3
        - name: latest
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (latest)
            description:
              MariaDB server builder for simple SQL database running under
              Fedora latest
            iconClass: icon-mariadb
            tags: builder,startx,alpine,mariadb,sql
            supports: mysql
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: ImageStreamTag
            name: rawhide
        - name: dev
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (dev)
            description: MariaDB server builder for simple SQL database (developpement)
            iconClass: icon-mariadb
            tags: builder,startx,alpine,mariadb,sql
            supports: mysql
            version: "dev"
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: ImageStreamTag
            name: rawhide
        - name: test
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (test)
            description: MariaDB server builder for simple SQL database (testing)
            iconClass: icon-mariadb
            tags: builder,startx,alpine,mariadb,sql
            supports: mysql
            version: "test"
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: ImageStreamTag
            name: centos8
        - name: preprod
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (preprod)
            description: MariaDB server builder for simple SQL database (pre-production)
            iconClass: icon-mariadb
            tags: builder,startx,alpine,mariadb,sql
            supports: mysql
            version: "pre-prod"
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: ImageStreamTag
            name: alpine3
        - name: prod
          annotations:
            openshift.io/display-name: S2I Startx Mariadb Database (prod)
            description: MariaDB server builder for simple SQL database (production)
            iconClass: icon-mariadb
            tags: builder,startx,alpine,mariadb,sql
            supports: mysql
            version: "prod"
            sampleRepo: https://github.com/startxfr/docker-images-example-mariadb.git
          from:
            kind: ImageStreamTag
            name: alpine3
