name: Docker Image CI
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1-5"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: "./travis/prepare-begin      fedora                   latest         rawhide"





  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
