name: Docker Image CI
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1-5"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  QUAY_USER: ${{ secrets.QUAY_USER }}
  QUAY_PASS: ${{ secrets.QUAY_PASS }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start
      run: "./travis/prepare-begin fedora latest rawhide"
    - name: Docker
      run: "./travis/prepare-docker fedora latest rawhide"
    - name: Dockerhub
      run: "./travis/prepare-dockerhub fedora latest rawhide"
    - name: Cache
      run: "./travis/prepare-cache fedora latest rawhide"
    - name: End
      run: "./travis/prepare-end fedora latest rawhide"
  publish-OS:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Connect-registry
      run: "./travis/prepare-dockerhub fedora latest rawhide"
    - name: build
      run: "./travis/test OS fedora latest fedora"
    - name: publish
      run: "./travis/publish OS fedora latest fedora"
