kind: Template
apiVersion: v1
metadata:
  name: startx-nodejs-build-template
  annotations:
    openshift.io/display-name: Startx MicroWeb (ephemeral build & deploy workflow)
    description:
      Build and deployement workflow of a micro-web application using ephemeral storage
      for logs records. Use nodejs with various underlying linux distribution. See
      https://hub.docker.com/r/startx/sv-nodejs
    iconClass: icon-nodejs
    tags: startx,os,fedora,nodejs,httpd
    openshift.io/provider-display-name: STARTX
    openshift.io/documentation-url: https://hub.docker.com/r/startx/sv-nodejs
    openshift.io/support-url: https://github.com/startxfr/docker-images/issues/new
message: |-
  Your application ${APP_NAME} is building and will be soon deployed.
  Monitor the deployement for application availability

  Source      : ${SOURCE_BRANCH}@${SOURCE_GIT}
  Application : ${APP_NAME}
  Stage       : ${APP_STAGE}
  Builder     : ${BUILDER_TAG}
  Volumes     : ${APP_NAME}-log (E), ${APP_NAME}-data (E)

  Connection  : http://${APP_NAME}:8080

labels:
  template: startx-nodejs-build-template
  provider: startx
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: startx-nodejs
      annotations:
        openshift.io/display-name: Startx Micro-WebServer
        openshift.io/generated-by: STARTX
      labels:
        app: "${APP_NAME}"
        stage: "${APP_STAGE}"
    spec:
      tags:
        - name: fc26
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (Fedora 26)
            description:
              Lightweight Http server builder for micro-web application running under
              Fedora 26
            iconClass: icon-nodejs
            tags: builder,startx,fedora,nodejs,httpd
            supports: http
            version: fc26
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:fc26
        - name: fc27
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (Fedora 27)
            description:
              Lightweight Http server builder for micro-web application running under
              Fedora 27
            iconClass: icon-nodejs
            tags: builder,startx,fedora,nodejs,httpd
            supports: http
            version: fc27
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:fc27
        - name: fc28
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (Fedora 28)
            description:
              Lightweight Http server builder for micro-web application running under
              Fedora 28
            iconClass: icon-nodejs
            tags: builder,startx,fedora,nodejs,httpd
            supports: http
            version: fc28
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:fc28
        - name: fc29
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (Fedora 29)
            description:
              Lightweight Http server builder for micro-web application running under
              Fedora 29
            iconClass: icon-nodejs
            tags: builder,startx,fedora,nodejs,httpd
            supports: http
            version: fc29
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:fc29
        - name: fc30
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (Fedora 30)
            description:
              Lightweight Http server builder for micro-web application running under
              Fedora 30
            iconClass: icon-nodejs
            tags: builder,startx,fedora,nodejs,httpd
            supports: http
            version: fc30
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:fc30
        - name: fc31
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (Fedora 31)
            description:
              Lightweight Http server builder for micro-web application running under
              Fedora 31
            iconClass: icon-nodejs
            tags: builder,startx,fedora,nodejs,httpd
            supports: http
            version: fc31
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:fc31
        - name: fc32
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (Fedora 32)
            description:
              Lightweight Http server builder for micro-web application running under
              Fedora 32
            iconClass: icon-nodejs
            tags: builder,startx,fedora,nodejs,httpd
            supports: http
            version: fc32
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:fc32
        - name: rawhide
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (Fedora rawhide)
            description:
              Lightweight Http server builder for micro-web application running under
              Fedora rawhide
            iconClass: icon-nodejs
            tags: builder,startx,fedora,nodejs,httpd
            supports: http
            version: rawhide
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:latest
        - name: ubi8
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (RedHat UBI 8)
            description:
              Lightweight Http server builder for micro-web application running under
              RedHat UBI 8
            iconClass: icon-nodejs
            tags: builder,startx,ubi,nodejs,httpd
            supports: http
            version: "8"
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:ubi8
        - name: centos8
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (Centos 8)
            description:
              Lightweight Http server builder for micro-web application running under
              Centos 8
            iconClass: icon-nodejs
            tags: builder,startx,centos,nodejs,httpd
            supports: http
            version: "8"
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:centos8
        - name: centos7
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (Centos 7)
            description:
              Lightweight Http server builder for micro-web application running under
              Centos 7
            iconClass: icon-nodejs
            tags: builder,startx,centos,nodejs,httpd
            supports: http
            version: "7"
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:centos7
        - name: centos6
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (Centos 6)
            description:
              Lightweight Http server builder for micro-web application running under
              Centos 6
            iconClass: icon-nodejs
            tags: builder,startx,centos,nodejs,httpd
            supports: http
            version: "6"
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:centos6
        - name: alpine3
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (Alpine 3)
            description:
              Lightweight Http server builder for micro-web application running under
              Alpine 3
            iconClass: icon-nodejs
            tags: builder,startx,alpine,nodejs,httpd
            supports: http
            version: "3"
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: DockerImage
            name: startx/sv-nodejs:alpine3
        - name: latest
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (latest)
            description:
              Lightweight Http server builder for micro-web application running under
              Fedora latest
            iconClass: icon-nodejs
            tags: builder,startx,alpine,nodejs,httpd
            supports: http
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: ImageStreamTag
            name: rawhide
        - name: dev
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (dev)
            description: Lightweight Http server builder for micro-web application (developpement)
            iconClass: icon-nodejs
            tags: builder,startx,alpine,nodejs,httpd
            supports: http
            version: "dev"
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: ImageStreamTag
            name: rawhide
        - name: test
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (test)
            description: Lightweight Http server builder for micro-web application (testing)
            iconClass: icon-nodejs
            tags: builder,startx,alpine,nodejs,httpd
            supports: http
            version: "test"
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: ImageStreamTag
            name: centos8
        - name: preprod
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (preprod)
            description: Lightweight Http server builder for micro-web application (pre-production)
            iconClass: icon-nodejs
            tags: builder,startx,alpine,nodejs,httpd
            supports: http
            version: "pre-prod"
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: ImageStreamTag
            name: alpine3
        - name: prod
          annotations:
            openshift.io/display-name: S2I Startx Micro-WebServer (prod)
            description: Lightweight Http server builder for micro-web application (production)
            iconClass: icon-nodejs
            tags: builder,startx,alpine,nodejs,httpd
            supports: http
            version: "prod"
            sampleRepo: https://github.com/startxfr/docker-images-example-nodejs.git
          from:
            kind: ImageStreamTag
            name: alpine3
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${APP_NAME}"
      annotations:
        openshift.io/display-name: Application ${APP_NAME}
        openshift.io/generated-by: STARTX
      labels:
        app: "${APP_NAME}"
        stage: "${APP_STAGE}"
    spec:
      tags:
        - name: latest
          annotations:
            openshift.io/display-name: Application ${APP_NAME}
            description: Base image for the application ${APP_NAME}
            iconClass: icon-nodejs
            tags: startx,fedora,nodejs,httpd,application,${APP_NAME}
            supports: http
            version: latest
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: "${APP_NAME}-config"
      annotations:
        openshift.io/display-name: Application ${APP_NAME} configuration
        openshift.io/generated-by: STARTX
      labels:
        app: "${APP_NAME}"
        stage: "${APP_STAGE}"
    data:
      SX_ID: ${APP_NAME}/${APP_STAGE}
      SX_TYPE: ${APP_STAGE}
      SX_SERVICE: ${APP_NAME}
      SX_NAME: Static web application ${APP_NAME}
      SX_SUMMARY: Static web application ${APP_NAME} based on fedora container
      SX_VERSION: 0.0.1
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${APP_NAME}"
      labels:
        app: "${APP_NAME}"
        stage: "${APP_STAGE}"
      annotations:
        openshift.io/generated-by: STARTX
    spec:
      triggers:
        - type: GitHub
          github:
            secret: "${WEBHOOK_TOKEN}_${APP_NAME}"
        - type: Generic
          generic:
            secret: "${WEBHOOK_TOKEN}_${APP_NAME}"
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
      runPolicy: SerialLatestOnly
      source:
        type: Git
        git:
          uri: "${SOURCE_GIT}"
          ref: "${SOURCE_BRANCH}"
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: startx-nodejs:${BUILDER_TAG}
          env:
            - name: SX_VERBOSE
              value: "true"
      output:
        to:
          kind: ImageStreamTag
          name: "${APP_NAME}:latest"
      postCommit:
        command:
          - "/bin/sx-nodejs"
          - post-build
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${APP_NAME}"
      labels:
        app: "${APP_NAME}"
        stage: "${APP_STAGE}"
      annotations:
        openshift.io/generated-by: STARTX
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 40
          maxUnavailable: 25%
          maxSurge: 25%
          pre:
            failurePolicy: Abort
            execNewPod:
              containerName: "${APP_NAME}"
              command:
                - "/bin/sx-nodejs"
                - pre-deploy
              env:
                - name: SX_VERBOSE
                  value: "true"
                - name: SX_DEBUG
                  value: "true"
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-config
          post:
            failurePolicy: Abort
            execNewPod:
              containerName: "${APP_NAME}"
              command:
                - "/bin/sx-nodejs"
                - post-deploy
              env:
                - name: SX_VERBOSE
                  value: "true"
                - name: SX_DEBUG
                  value: "true"
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-config
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${APP_NAME}"
            from:
              kind: ImageStreamTag
              name: "${APP_NAME}:latest"
        - type: ConfigChange
      postCommit:
        script: "/bin/sx-nodejs info"
      replicas: 1
      test: false
      selector:
        app: "${APP_NAME}"
        deploymentconfig: "${APP_NAME}"
      template:
        metadata:
          labels:
            app: "${APP_NAME}"
            deploymentconfig: "${APP_NAME}"
          annotations:
            openshift.io/generated-by: STARTX
        spec:
          containers:
            - name: "${APP_NAME}"
              image: " "
              env:
                - name: SX_VERBOSE
                  value: "true"
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-config
              command:
                - "/bin/sx-nodejs"
              args:
                - run
              ports:
                - containerPort: 8080
                  protocol: TCP
              livenessProbe:
                exec:
                  command:
                    - "/bin/sx-nodejs"
                    - isLive
                initialDelaySeconds: 4
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                exec:
                  command:
                    - "/bin/sx-nodejs"
                    - isReady
                initialDelaySeconds: 4
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              resources:
                limits:
                  cpu: 1000m
                  memory: "${MEMORY_LIMIT}"
                requests:
                  cpu: 200m
                  memory: "${MEMORY_LIMIT}"
              terminationMessagePath: "/dev/termination-log"
              imagePullPolicy: Always
              volumeMounts:
                - name: "${APP_NAME}-log"
                  mountPath: "/var/log/httpd"
          volumes:
            - name: "${APP_NAME}-log"
              emptyDir:
                medium: ""
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          securityContext: {}
          dnsPolicy: ClusterFirst
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APP_NAME}"
      labels:
        app: "${APP_NAME}"
        stage: "${APP_STAGE}"
      annotations:
        openshift.io/generated-by: STARTX
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: "${APP_NAME}"
        deploymentconfig: "${APP_NAME}"
      type: ClusterIP
      sessionAffinity: None
  - kind: Route
    apiVersion: v1
    metadata:
      name: "${APP_NAME}"
      labels:
        app: "${APP_NAME}"
        stage: "${APP_STAGE}"
      annotations:
        openshift.io/generated-by: STARTX
    spec:
      to:
        kind: Service
        name: "${APP_NAME}"
        weight: 100
parameters:
  - name: APP_NAME
    displayName: Application name
    description: The name of the created application
    value: nodejs
    required: true
  - name: APP_STAGE
    displayName: Application stage
    description: "Stage of the application deployed (ex: dev, test, prod, example, demo, poc, ...)"
    value: example
    required: true
  - name: BUILDER_TAG
    displayName: Builder image stage
    description: "Image tag of the startx nodejs builder image used. Could be : latest, dev, test, preprod, prod - rawhide, fc31, fc30, fc29, fc28 - alpine3 - ubi8 - centos8, centos7, centos6)"
    value: latest
    required: true
  - name: SOURCE_GIT
    displayName: Source repository
    description: URL to the source code to use during build process
    value: https://github.com/startxfr/docker-images-example-nodejs.git
    required: true
  - name: SOURCE_BRANCH
    displayName: Source branch
    description: Name of the default branch
    value: master
    required: true
  - name: WEBHOOK_TOKEN
    displayName: Webhook token
    description: Secret token to use for webhook to github or generic
    generate: expression
    from: "[a-zA-Z0-9]{24}"
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use. e.g. 512Mi, 2Gi.
    value: 256Mi
    required: true
