##
## STAGES
##

# Build the phpmyadmin application image
build-application-phpmyadmin-latest:
  stage: "build Application"
  extends: .build-image-latest
  allow_failure: true
  variables:
    SXDI_PATH: "Applications/phpmyadmin"
    SXDI_DOCKERNAME: "app-phpmyadmin"
    SXDI_QUAYNAME: "phpmyadmin"
    SXDI_ENGINE: docker
  only:
    - master
build-application-phpmyadmin:
  stage: "build Application"
  extends: .build-image
  allow_failure: true
  variables:
    SXDI_PATH: "Applications/phpmyadmin"
    SXDI_DOCKERNAME: "app-phpmyadmin"
    SXDI_QUAYNAME: "phpmyadmin"
    SXDI_ENGINE: docker
  only:
    - alma
    - rocky
    - centos8
    - centos7
    - centos6
    - alpine
    - ubi8
    - fc36
    - fc35
    - fc34
    - fc33
    - fc32
    - fc31
    - fc30
    - fc29
    - fc28
    - fc27
    - fc26
    - fc25
    - fc24
    - fc23
    - fc22

# Build the ocp-reliability application image
build-application-ocp-reliability-latest:
  stage: "build OCP reliability"
  extends: .build-image-latest
  allow_failure: true
  variables:
    SXDI_PATH: "Applications/ocp-reliability"
    SXDI_DOCKERNAME: "app-ocp-reliability"
    SXDI_QUAYNAME: "ocp-reliability"
    SXDI_ENGINE: docker
  only:
    - master
build-application-ocp-reliability:
  stage: "build OCP reliability"
  extends: .build-image
  allow_failure: true
  variables:
    SXDI_PATH: "Applications/ocp-reliability"
    SXDI_DOCKERNAME: "app-ocp-reliability"
    SXDI_QUAYNAME: "ocp-reliability"
    SXDI_ENGINE: docker
  only:
    - alma
    - rocky
    - centos8
    - centos7
    - centos6
    - alpine
    - ubi8
    - fc36
    - fc35
