##
## STAGES
##

# Build the phpmyadmin application image
build-application-phpmyadmin-latest:
  stage: "build Application"
  extends: .build-image-latest
  allow_failure: true
  variables:
    SXDI_PATH: "Applications/phpmyadmin"
    SXDI_DOCKERNAME: "app-phpmyadmin"
    SXDI_QUAYNAME: "phpmyadmin"
    SXDI_ENGINE: docker
  only:
    - master
build-application-phpmyadmin-latest-sign:
  stage: "build Application"
  extends: .build-image-sign-latest
  needs: 
    - "build-application-phpmyadmin-latest"
  allow_failure: true
  variables:
    SXDI_PATH: "Applications/phpmyadmin"
    SXDI_DOCKERNAME: "app-phpmyadmin"
    SXDI_QUAYNAME: "phpmyadmin"
    SXDI_ENGINE: docker
  only:
    - master
build-application-phpmyadmin:
  stage: "build Application"
  extends: .build-image
  allow_failure: true
  variables:
    SXDI_PATH: "Applications/phpmyadmin"
    SXDI_DOCKERNAME: "app-phpmyadmin"
    SXDI_QUAYNAME: "phpmyadmin"
    SXDI_ENGINE: docker
  only:
    - alma
    - rocky
    - centos8
    - centos7
    - centos6
    - alpine
    - ubi8
    - fc41
    - fc40
    - fc39
    - fc38
    - fc37
    - fc36
    - fc35
    - fc34
    - fc33
build-application-phpmyadmin-sign:
  stage: "build Application"
  extends: .build-image-sign
  needs: 
    - "build-application-phpmyadmin"
  allow_failure: true
  variables:
    SXDI_PATH: "Applications/phpmyadmin"
    SXDI_DOCKERNAME: "app-phpmyadmin"
    SXDI_QUAYNAME: "phpmyadmin"
    SXDI_ENGINE: docker
  only:
    - alma
    - rocky
    - centos8
    - centos7
    - centos6
    - alpine
    - ubi8
    - fc41
    - fc40
    - fc39
    - fc38
    - fc37
    - fc36
    - fc35
    - fc34
    - fc33

# Build the ocp-reliability application image
build-application-ocp-reliability-latest:
  stage: "build Application"
  extends: .build-image-latest
  allow_failure: true
  variables:
    SXDI_PATH: "Applications/ocp-reliability"
    SXDI_DOCKERNAME: "app-ocp-reliability"
    SXDI_QUAYNAME: "ocp-reliability"
    SXDI_ENGINE: docker
  only:
    - master
build-application-ocp-reliability-latest-sign:
  stage: "build Application"
  extends: .build-image-sign-latest
  needs: 
    - "build-application-ocp-reliability-latest"
  allow_failure: true
  variables:
    SXDI_PATH: "Applications/ocp-reliability"
    SXDI_DOCKERNAME: "app-ocp-reliability"
    SXDI_QUAYNAME: "ocp-reliability"
    SXDI_ENGINE: docker
  only:
    - master
build-application-ocp-reliability:
  stage: "build Application"
  extends: .build-image
  allow_failure: true
  variables:
    SXDI_PATH: "Applications/ocp-reliability"
    SXDI_DOCKERNAME: "app-ocp-reliability"
    SXDI_QUAYNAME: "ocp-reliability"
    SXDI_ENGINE: docker
  only:
    - alma
    - rocky
    - centos8
    - centos7
    - centos6
    - alpine
    - ubi8
    - fc41
    - fc40
    - fc39
    - fc38
    - fc37
    - fc36
    - fc35
build-application-ocp-reliability-sign:
  stage: "build Application"
  extends: .build-image-sign
  needs: 
    - "build-application-ocp-reliability"
  allow_failure: true
  variables:
    SXDI_PATH: "Applications/ocp-reliability"
    SXDI_DOCKERNAME: "app-ocp-reliability"
    SXDI_QUAYNAME: "ocp-reliability"
    SXDI_ENGINE: docker
  only:
    - alma
    - rocky
    - centos8
    - centos7
    - centos6
    - alpine
    - ubi8
    - fc41
    - fc40
    - fc39
    - fc38
    - fc37
    - fc36
    - fc35
